/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Skautik.Sdk.Client;
using Skautik.Sdk.Model;

namespace Skautik.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExportsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Request an export
        /// </summary>
        /// <remarks>
        /// Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <returns>Envelope</returns>
        Envelope CreateExport(CreateExportRequest createExportRequest);

        /// <summary>
        /// Request an export
        /// </summary>
        /// <remarks>
        /// Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> CreateExportWithHttpInfo(CreateExportRequest createExportRequest);
        /// <summary>
        /// Retrieve an export
        /// </summary>
        /// <remarks>
        /// Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <returns>Envelope</returns>
        Envelope GetExport(string exportId);

        /// <summary>
        /// Retrieve an export
        /// </summary>
        /// <remarks>
        /// Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <returns>ApiResponse of Envelope</returns>
        ApiResponse<Envelope> GetExportWithHttpInfo(string exportId);
        /// <summary>
        /// List exports
        /// </summary>
        /// <remarks>
        /// Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ListExports();

        /// <summary>
        /// List exports
        /// </summary>
        /// <remarks>
        /// Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ListExportsWithHttpInfo();
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExportsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Request an export
        /// </summary>
        /// <remarks>
        /// Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> CreateExportAsync(CreateExportRequest createExportRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Request an export
        /// </summary>
        /// <remarks>
        /// Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> CreateExportWithHttpInfoAsync(CreateExportRequest createExportRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieve an export
        /// </summary>
        /// <remarks>
        /// Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        System.Threading.Tasks.Task<Envelope> GetExportAsync(string exportId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve an export
        /// </summary>
        /// <remarks>
        /// Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        System.Threading.Tasks.Task<ApiResponse<Envelope>> GetExportWithHttpInfoAsync(string exportId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List exports
        /// </summary>
        /// <remarks>
        /// Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ListExportsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List exports
        /// </summary>
        /// <remarks>
        /// Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </remarks>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ListExportsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IExportsApi : IExportsApiSync, IExportsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ExportsApi : IDisposable, IExportsApi
    {
        private Skautik.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ExportsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ExportsApi(string basePath)
        {
            this.Configuration = Skautik.Sdk.Client.Configuration.MergeConfigurations(
                Skautik.Sdk.Client.GlobalConfiguration.Instance,
                new Skautik.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Skautik.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Skautik.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ExportsApi(Skautik.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Skautik.Sdk.Client.Configuration.MergeConfigurations(
                Skautik.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Skautik.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Skautik.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ExportsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ExportsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Skautik.Sdk.Client.Configuration.MergeConfigurations(
                Skautik.Sdk.Client.GlobalConfiguration.Instance,
                new Skautik.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Skautik.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Skautik.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ExportsApi(HttpClient client, Skautik.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Skautik.Sdk.Client.Configuration.MergeConfigurations(
                Skautik.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Skautik.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Skautik.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ExportsApi(Skautik.Sdk.Client.ISynchronousClient client, Skautik.Sdk.Client.IAsynchronousClient asyncClient, Skautik.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Skautik.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Skautik.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Skautik.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Skautik.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Skautik.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Skautik.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Request an export Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <returns>Envelope</returns>
        public Envelope CreateExport(CreateExportRequest createExportRequest)
        {
            Skautik.Sdk.Client.ApiResponse<Envelope> localVarResponse = CreateExportWithHttpInfo(createExportRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request an export Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <returns>ApiResponse of Envelope</returns>
        public Skautik.Sdk.Client.ApiResponse<Envelope> CreateExportWithHttpInfo(CreateExportRequest createExportRequest)
        {
            // verify the required parameter 'createExportRequest' is set
            if (createExportRequest == null)
                throw new Skautik.Sdk.Client.ApiException(400, "Missing required parameter 'createExportRequest' when calling ExportsApi->CreateExport");

            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createExportRequest;

            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Envelope>("/exports", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateExport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request an export Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> CreateExportAsync(CreateExportRequest createExportRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Skautik.Sdk.Client.ApiResponse<Envelope> localVarResponse = await CreateExportWithHttpInfoAsync(createExportRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request an export Queue a bulk extract of the catalogue.  Accepts the same filters as the list endpoint. Returns immediately with a pending export; subscribe to export.completed rather than polling. Note that a narrowed field set may not round trip: feeding an export back into an import needs the columns an import requires, external_id and type among them, so omit fields for analysis rather than for a re-import.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createExportRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<Skautik.Sdk.Client.ApiResponse<Envelope>> CreateExportWithHttpInfoAsync(CreateExportRequest createExportRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createExportRequest' is set
            if (createExportRequest == null)
                throw new Skautik.Sdk.Client.ApiException(400, "Missing required parameter 'createExportRequest' when calling ExportsApi->CreateExport");


            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createExportRequest;

            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Envelope>("/exports", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateExport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve an export Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <returns>Envelope</returns>
        public Envelope GetExport(string exportId)
        {
            Skautik.Sdk.Client.ApiResponse<Envelope> localVarResponse = GetExportWithHttpInfo(exportId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve an export Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <returns>ApiResponse of Envelope</returns>
        public Skautik.Sdk.Client.ApiResponse<Envelope> GetExportWithHttpInfo(string exportId)
        {
            // verify the required parameter 'exportId' is set
            if (exportId == null)
                throw new Skautik.Sdk.Client.ApiException(400, "Missing required parameter 'exportId' when calling ExportsApi->GetExport");

            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("export_id", Skautik.Sdk.Client.ClientUtils.ParameterToString(exportId)); // path parameter

            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Envelope>("/exports/{export_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetExport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve an export Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Envelope</returns>
        public async System.Threading.Tasks.Task<Envelope> GetExportAsync(string exportId, System.Threading.CancellationToken cancellationToken = default)
        {
            Skautik.Sdk.Client.ApiResponse<Envelope> localVarResponse = await GetExportWithHttpInfoAsync(exportId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve an export Status, and the download URL once it is ready.  Download URLs are signed and expire one hour after issue, and are minted per request rather than stored, so ask again if one lapses. The file itself is kept for seven days; after that the export still appears in your history with no link, because the object has been swept.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="exportId">Export identifier.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Envelope)</returns>
        public async System.Threading.Tasks.Task<Skautik.Sdk.Client.ApiResponse<Envelope>> GetExportWithHttpInfoAsync(string exportId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'exportId' is set
            if (exportId == null)
                throw new Skautik.Sdk.Client.ApiException(400, "Missing required parameter 'exportId' when calling ExportsApi->GetExport");


            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("export_id", Skautik.Sdk.Client.ClientUtils.ParameterToString(exportId)); // path parameter

            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Envelope>("/exports/{export_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetExport", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List exports Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ListExports()
        {
            ListExportsWithHttpInfo();
        }

        /// <summary>
        /// List exports Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public Skautik.Sdk.Client.ApiResponse<Object> ListExportsWithHttpInfo()
        {
            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };

            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/exports", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListExports", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List exports Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ListExportsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            await ListExportsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// List exports Recent exports for your organisation, newest first.  Statuses only. Download links are not included here: minting one per row would sign a URL for every export you have ever made on a call you probably wanted statuses from. Fetch the export itself for a link.  Requires the &#x60;exports:create&#x60; scope.
        /// </summary>
        /// <exception cref="Skautik.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Skautik.Sdk.Client.ApiResponse<Object>> ListExportsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Skautik.Sdk.Client.RequestOptions localVarRequestOptions = new Skautik.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/problem+json"
            };


            var localVarContentType = Skautik.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Skautik.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (apiKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/exports", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListExports", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
