// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Address
    /// </summary>
    public partial class Address : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Address" /> class.
        /// </summary>
        /// <param name="city">city</param>
        /// <param name="country">country</param>
        /// <param name="district">district</param>
        /// <param name="number">number</param>
        /// <param name="postalCode">postalCode</param>
        /// <param name="province">province</param>
        /// <param name="street">street</param>
        [JsonConstructor]
        public Address(Option<string?> city = default, Option<string?> country = default, Option<string?> district = default, Option<string?> number = default, Option<string?> postalCode = default, Option<string?> province = default, Option<string?> street = default)
        {
            CityOption = city;
            CountryOption = country;
            DistrictOption = district;
            NumberOption = number;
            PostalCodeOption = postalCode;
            ProvinceOption = province;
            StreetOption = street;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of City
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CityOption { get; private set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [JsonPropertyName("city")]
        public string? City { get { return this.CityOption.Value; } set { this.CityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of District
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DistrictOption { get; private set; }

        /// <summary>
        /// Gets or Sets District
        /// </summary>
        [JsonPropertyName("district")]
        public string? District { get { return this.DistrictOption.Value; } set { this.DistrictOption = new(value); } }

        /// <summary>
        /// Used to track the state of Number
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [JsonPropertyName("number")]
        public string? Number { get { return this.NumberOption.Value; } set { this.NumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of PostalCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PostalCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        [JsonPropertyName("postal_code")]
        public string? PostalCode { get { return this.PostalCodeOption.Value; } set { this.PostalCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Province
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProvinceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Province
        /// </summary>
        [JsonPropertyName("province")]
        public string? Province { get { return this.ProvinceOption.Value; } set { this.ProvinceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Street
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StreetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Street
        /// </summary>
        [JsonPropertyName("street")]
        public string? Street { get { return this.StreetOption.Value; } set { this.StreetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Address {\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  District: ").Append(District).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  Province: ").Append(Province).Append("\n");
            sb.Append("  Street: ").Append(Street).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Address" />
    /// </summary>
    public partial class AddressJsonConverter : JsonConverter<Address>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressJsonConverter" /> class.
        /// </summary>
        public AddressJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Address" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Address Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> city = default;
            Option<string?> country = default;
            Option<string?> district = default;
            Option<string?> number = default;
            Option<string?> postalCode = default;
            Option<string?> province = default;
            Option<string?> street = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "city":
                            city = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "district":
                            district = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "number":
                            number = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "postal_code":
                            postalCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "province":
                            province = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "street":
                            street = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (city.IsSet && city.Value == null)
                throw new ArgumentNullException(nameof(city), "Property is not nullable for class Address.");

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class Address.");

            if (district.IsSet && district.Value == null)
                throw new ArgumentNullException(nameof(district), "Property is not nullable for class Address.");

            if (number.IsSet && number.Value == null)
                throw new ArgumentNullException(nameof(number), "Property is not nullable for class Address.");

            if (postalCode.IsSet && postalCode.Value == null)
                throw new ArgumentNullException(nameof(postalCode), "Property is not nullable for class Address.");

            if (province.IsSet && province.Value == null)
                throw new ArgumentNullException(nameof(province), "Property is not nullable for class Address.");

            if (street.IsSet && street.Value == null)
                throw new ArgumentNullException(nameof(street), "Property is not nullable for class Address.");

            return new Address(city, country, district, number, postalCode, province, street);
        }

        /// <summary>
        /// Serializes a <see cref="Address" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="address"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Address address, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, address, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Address" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="address"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Address address, JsonSerializerOptions jsonSerializerOptions)
        {
            if (address.CityOption.IsSet && address.City == null)
                throw new ArgumentNullException(nameof(address.City), "Property is required for class Address.");

            if (address.CountryOption.IsSet && address.Country == null)
                throw new ArgumentNullException(nameof(address.Country), "Property is required for class Address.");

            if (address.DistrictOption.IsSet && address.District == null)
                throw new ArgumentNullException(nameof(address.District), "Property is required for class Address.");

            if (address.NumberOption.IsSet && address.Number == null)
                throw new ArgumentNullException(nameof(address.Number), "Property is required for class Address.");

            if (address.PostalCodeOption.IsSet && address.PostalCode == null)
                throw new ArgumentNullException(nameof(address.PostalCode), "Property is required for class Address.");

            if (address.ProvinceOption.IsSet && address.Province == null)
                throw new ArgumentNullException(nameof(address.Province), "Property is required for class Address.");

            if (address.StreetOption.IsSet && address.Street == null)
                throw new ArgumentNullException(nameof(address.Street), "Property is required for class Address.");

            if (address.CityOption.IsSet)
                writer.WriteString("city", address.City);

            if (address.CountryOption.IsSet)
                writer.WriteString("country", address.Country);

            if (address.DistrictOption.IsSet)
                writer.WriteString("district", address.District);

            if (address.NumberOption.IsSet)
                writer.WriteString("number", address.Number);

            if (address.PostalCodeOption.IsSet)
                writer.WriteString("postal_code", address.PostalCode);

            if (address.ProvinceOption.IsSet)
                writer.WriteString("province", address.Province);

            if (address.StreetOption.IsSet)
                writer.WriteString("street", address.Street);
        }
    }
}
