// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Bounds
    /// </summary>
    public partial class Bounds : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Bounds" /> class.
        /// </summary>
        /// <param name="neLat">neLat</param>
        /// <param name="neLng">neLng</param>
        /// <param name="swLat">swLat</param>
        /// <param name="swLng">swLng</param>
        [JsonConstructor]
        public Bounds(decimal neLat, decimal neLng, decimal swLat, decimal swLng)
        {
            NeLat = neLat;
            NeLng = neLng;
            SwLat = swLat;
            SwLng = swLng;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NeLat
        /// </summary>
        [JsonPropertyName("ne_lat")]
        public decimal NeLat { get; set; }

        /// <summary>
        /// Gets or Sets NeLng
        /// </summary>
        [JsonPropertyName("ne_lng")]
        public decimal NeLng { get; set; }

        /// <summary>
        /// Gets or Sets SwLat
        /// </summary>
        [JsonPropertyName("sw_lat")]
        public decimal SwLat { get; set; }

        /// <summary>
        /// Gets or Sets SwLng
        /// </summary>
        [JsonPropertyName("sw_lng")]
        public decimal SwLng { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Bounds {\n");
            sb.Append("  NeLat: ").Append(NeLat).Append("\n");
            sb.Append("  NeLng: ").Append(NeLng).Append("\n");
            sb.Append("  SwLat: ").Append(SwLat).Append("\n");
            sb.Append("  SwLng: ").Append(SwLng).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Bounds" />
    /// </summary>
    public partial class BoundsJsonConverter : JsonConverter<Bounds>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BoundsJsonConverter" /> class.
        /// </summary>
        public BoundsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Bounds" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Bounds Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> neLat = default;
            Option<decimal?> neLng = default;
            Option<decimal?> swLat = default;
            Option<decimal?> swLng = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ne_lat":
                            neLat = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "ne_lng":
                            neLng = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "sw_lat":
                            swLat = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "sw_lng":
                            swLng = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!neLat.IsSet)
                throw new ArgumentException("Property is required for class Bounds.", nameof(neLat));

            if (!neLng.IsSet)
                throw new ArgumentException("Property is required for class Bounds.", nameof(neLng));

            if (!swLat.IsSet)
                throw new ArgumentException("Property is required for class Bounds.", nameof(swLat));

            if (!swLng.IsSet)
                throw new ArgumentException("Property is required for class Bounds.", nameof(swLng));

            if (neLat.IsSet && neLat.Value == null)
                throw new ArgumentNullException(nameof(neLat), "Property is not nullable for class Bounds.");

            if (neLng.IsSet && neLng.Value == null)
                throw new ArgumentNullException(nameof(neLng), "Property is not nullable for class Bounds.");

            if (swLat.IsSet && swLat.Value == null)
                throw new ArgumentNullException(nameof(swLat), "Property is not nullable for class Bounds.");

            if (swLng.IsSet && swLng.Value == null)
                throw new ArgumentNullException(nameof(swLng), "Property is not nullable for class Bounds.");

            return new Bounds(neLat.Value!.Value!, neLng.Value!.Value!, swLat.Value!.Value!, swLng.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Bounds" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bounds"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Bounds bounds, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, bounds, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Bounds" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="bounds"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Bounds bounds, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("ne_lat", bounds.NeLat);

            writer.WriteNumber("ne_lng", bounds.NeLng);

            writer.WriteNumber("sw_lat", bounds.SwLat);

            writer.WriteNumber("sw_lng", bounds.SwLng);
        }
    }
}
