/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// CreatePropertyRequest
    /// </summary>
    [DataContract(Name = "createProperty_request")]
    public partial class CreatePropertyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePropertyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePropertyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePropertyRequest" /> class.
        /// </summary>
        /// <param name="address">At minimum a city and country; more improves geocoding precision. (required).</param>
        /// <param name="currency">ISO 4217 code. (required).</param>
        /// <param name="externalId">Your identifier for this property. Optional, but set it if the record might later arrive through an import: without one the import has nothing to match on and creates a duplicate..</param>
        /// <param name="price">Amount in minor units. (required).</param>
        /// <param name="propertyType">One of the supported property types. (required).</param>
        /// <param name="title">Headline for the listing. (required).</param>
        /// <param name="transactionType">sale or rent. (required).</param>
        public CreatePropertyRequest(Dictionary<string, Object> address = default, string currency = default, string externalId = default, int price = default, string propertyType = default, string title = default, string transactionType = default)
        {
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for CreatePropertyRequest and cannot be null");
            }
            this.Address = address;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CreatePropertyRequest and cannot be null");
            }
            this.Currency = currency;
            this.Price = price;
            // to ensure "propertyType" is required (not null)
            if (propertyType == null)
            {
                throw new ArgumentNullException("propertyType is a required property for CreatePropertyRequest and cannot be null");
            }
            this.PropertyType = propertyType;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for CreatePropertyRequest and cannot be null");
            }
            this.Title = title;
            // to ensure "transactionType" is required (not null)
            if (transactionType == null)
            {
                throw new ArgumentNullException("transactionType is a required property for CreatePropertyRequest and cannot be null");
            }
            this.TransactionType = transactionType;
            this.ExternalId = externalId;
        }

        /// <summary>
        /// At minimum a city and country; more improves geocoding precision.
        /// </summary>
        /// <value>At minimum a city and country; more improves geocoding precision.</value>
        /*
        <example>{&quot;city&quot;:&quot;Berlin&quot;,&quot;country&quot;:&quot;DE&quot;,&quot;postal_code&quot;:&quot;10999&quot;,&quot;street&quot;:&quot;Oranienstrasse 12&quot;}</example>
        */
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Address { get; set; }

        /// <summary>
        /// ISO 4217 code.
        /// </summary>
        /// <value>ISO 4217 code.</value>
        /*
        <example>EUR</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Your identifier for this property. Optional, but set it if the record might later arrive through an import: without one the import has nothing to match on and creates a duplicate.
        /// </summary>
        /// <value>Your identifier for this property. Optional, but set it if the record might later arrive through an import: without one the import has nothing to match on and creates a duplicate.</value>
        /*
        <example>AG-4471-0812</example>
        */
        [DataMember(Name = "external_id", EmitDefaultValue = false)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Amount in minor units.
        /// </summary>
        /// <value>Amount in minor units.</value>
        /*
        <example>48900000</example>
        */
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public int Price { get; set; }

        /// <summary>
        /// One of the supported property types.
        /// </summary>
        /// <value>One of the supported property types.</value>
        /*
        <example>apartment</example>
        */
        [DataMember(Name = "property_type", IsRequired = true, EmitDefaultValue = true)]
        public string PropertyType { get; set; }

        /// <summary>
        /// Headline for the listing.
        /// </summary>
        /// <value>Headline for the listing.</value>
        /*
        <example>Top-floor apartment with a south-facing balcony</example>
        */
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// sale or rent.
        /// </summary>
        /// <value>sale or rent.</value>
        /*
        <example>sale</example>
        */
        [DataMember(Name = "transaction_type", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePropertyRequest {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PropertyType: ").Append(PropertyType).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
