/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// CreateGenerationRequest
    /// </summary>
    [DataContract(Name = "createGeneration_request")]
    public partial class CreateGenerationRequest : IValidatableObject
    {
        /// <summary>
        /// The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.
        /// </summary>
        /// <value>The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KindEnum
        {
            /// <summary>
            /// Enum VirtualStaging for value: virtual_staging
            /// </summary>
            [EnumMember(Value = "virtual_staging")]
            VirtualStaging = 1,

            /// <summary>
            /// Enum Decluttering for value: decluttering
            /// </summary>
            [EnumMember(Value = "decluttering")]
            Decluttering = 2,

            /// <summary>
            /// Enum Enhancement for value: enhancement
            /// </summary>
            [EnumMember(Value = "enhancement")]
            Enhancement = 3
        }


        /// <summary>
        /// The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.
        /// </summary>
        /// <value>The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan.</value>
        /*
        <example>virtual_staging</example>
        */
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public KindEnum Kind { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateGenerationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateGenerationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateGenerationRequest" /> class.
        /// </summary>
        /// <param name="kind">The transformation to apply. floorplan_render is named in the schema and is not implemented; asking for it is refused rather than answered with a fabricated plan. (required).</param>
        /// <param name="prompt">Up to 500 characters of additional direction. It is added to the instruction for the chosen kind and never replaces it, so it cannot be used to make the model do something unrelated..</param>
        /// <param name="roomType">For virtual_staging: what the room is. Improves the result markedly. Defaults to a generic room..</param>
        /// <param name="sourceImageId">The image to transform. Must belong to one of your own properties; anything else answers 404, the same as an image that does not exist. (required).</param>
        /// <param name="style">For virtual_staging: the furnishing style. Defaults to contemporary..</param>
        public CreateGenerationRequest(KindEnum kind = default, string prompt = default, string roomType = default, string sourceImageId = default, string style = default)
        {
            this.Kind = kind;
            // to ensure "sourceImageId" is required (not null)
            if (sourceImageId == null)
            {
                throw new ArgumentNullException("sourceImageId is a required property for CreateGenerationRequest and cannot be null");
            }
            this.SourceImageId = sourceImageId;
            this.Prompt = prompt;
            this.RoomType = roomType;
            this.Style = style;
        }

        /// <summary>
        /// Up to 500 characters of additional direction. It is added to the instruction for the chosen kind and never replaces it, so it cannot be used to make the model do something unrelated.
        /// </summary>
        /// <value>Up to 500 characters of additional direction. It is added to the instruction for the chosen kind and never replaces it, so it cannot be used to make the model do something unrelated.</value>
        /*
        <example>A bright Scandinavian living room with oak floors and a linen sofa</example>
        */
        [DataMember(Name = "prompt", EmitDefaultValue = false)]
        public string Prompt { get; set; }

        /// <summary>
        /// For virtual_staging: what the room is. Improves the result markedly. Defaults to a generic room.
        /// </summary>
        /// <value>For virtual_staging: what the room is. Improves the result markedly. Defaults to a generic room.</value>
        /*
        <example>living room</example>
        */
        [DataMember(Name = "room_type", EmitDefaultValue = false)]
        public string RoomType { get; set; }

        /// <summary>
        /// The image to transform. Must belong to one of your own properties; anything else answers 404, the same as an image that does not exist.
        /// </summary>
        /// <value>The image to transform. Must belong to one of your own properties; anything else answers 404, the same as an image that does not exist.</value>
        /*
        <example>img_ce1c9e04db6140eda7c6934af60daebb</example>
        */
        [DataMember(Name = "source_image_id", IsRequired = true, EmitDefaultValue = true)]
        public string SourceImageId { get; set; }

        /// <summary>
        /// For virtual_staging: the furnishing style. Defaults to contemporary.
        /// </summary>
        /// <value>For virtual_staging: the furnishing style. Defaults to contemporary.</value>
        /*
        <example>scandinavian</example>
        */
        [DataMember(Name = "style", EmitDefaultValue = false)]
        public string Style { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateGenerationRequest {\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  RoomType: ").Append(RoomType).Append("\n");
            sb.Append("  SourceImageId: ").Append(SourceImageId).Append("\n");
            sb.Append("  Style: ").Append(Style).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
