// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Features
    /// </summary>
    public partial class Features : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Features" /> class.
        /// </summary>
        /// <param name="airConditioning">airConditioning</param>
        /// <param name="alarmSystem">alarmSystem</param>
        /// <param name="balcony">balcony</param>
        /// <param name="barrierFree">barrierFree</param>
        /// <param name="cellar">cellar</param>
        /// <param name="fireplace">fireplace</param>
        /// <param name="fittedKitchen">fittedKitchen</param>
        /// <param name="flooring">flooring</param>
        /// <param name="furnished">furnished</param>
        /// <param name="garden">garden</param>
        /// <param name="guestToilet">guestToilet</param>
        /// <param name="kitchenType">kitchenType</param>
        /// <param name="lift">lift</param>
        /// <param name="pool">pool</param>
        /// <param name="sauna">sauna</param>
        /// <param name="solarPanels">solarPanels</param>
        /// <param name="terrace">terrace</param>
        /// <param name="windowGlazing">windowGlazing</param>
        [JsonConstructor]
        public Features(Option<bool?> airConditioning = default, Option<bool?> alarmSystem = default, Option<bool?> balcony = default, Option<bool?> barrierFree = default, Option<bool?> cellar = default, Option<bool?> fireplace = default, Option<bool?> fittedKitchen = default, Option<string?> flooring = default, Option<bool?> furnished = default, Option<bool?> garden = default, Option<bool?> guestToilet = default, Option<string?> kitchenType = default, Option<bool?> lift = default, Option<bool?> pool = default, Option<bool?> sauna = default, Option<bool?> solarPanels = default, Option<bool?> terrace = default, Option<string?> windowGlazing = default)
        {
            AirConditioningOption = airConditioning;
            AlarmSystemOption = alarmSystem;
            BalconyOption = balcony;
            BarrierFreeOption = barrierFree;
            CellarOption = cellar;
            FireplaceOption = fireplace;
            FittedKitchenOption = fittedKitchen;
            FlooringOption = flooring;
            FurnishedOption = furnished;
            GardenOption = garden;
            GuestToiletOption = guestToilet;
            KitchenTypeOption = kitchenType;
            LiftOption = lift;
            PoolOption = pool;
            SaunaOption = sauna;
            SolarPanelsOption = solarPanels;
            TerraceOption = terrace;
            WindowGlazingOption = windowGlazing;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AirConditioning
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AirConditioningOption { get; private set; }

        /// <summary>
        /// Gets or Sets AirConditioning
        /// </summary>
        [JsonPropertyName("air_conditioning")]
        public bool? AirConditioning { get { return this.AirConditioningOption.Value; } set { this.AirConditioningOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlarmSystem
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AlarmSystemOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlarmSystem
        /// </summary>
        [JsonPropertyName("alarm_system")]
        public bool? AlarmSystem { get { return this.AlarmSystemOption.Value; } set { this.AlarmSystemOption = new(value); } }

        /// <summary>
        /// Used to track the state of Balcony
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BalconyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Balcony
        /// </summary>
        [JsonPropertyName("balcony")]
        public bool? Balcony { get { return this.BalconyOption.Value; } set { this.BalconyOption = new(value); } }

        /// <summary>
        /// Used to track the state of BarrierFree
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> BarrierFreeOption { get; private set; }

        /// <summary>
        /// Gets or Sets BarrierFree
        /// </summary>
        [JsonPropertyName("barrier_free")]
        public bool? BarrierFree { get { return this.BarrierFreeOption.Value; } set { this.BarrierFreeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cellar
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CellarOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cellar
        /// </summary>
        [JsonPropertyName("cellar")]
        public bool? Cellar { get { return this.CellarOption.Value; } set { this.CellarOption = new(value); } }

        /// <summary>
        /// Used to track the state of Fireplace
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FireplaceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fireplace
        /// </summary>
        [JsonPropertyName("fireplace")]
        public bool? Fireplace { get { return this.FireplaceOption.Value; } set { this.FireplaceOption = new(value); } }

        /// <summary>
        /// Used to track the state of FittedKitchen
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FittedKitchenOption { get; private set; }

        /// <summary>
        /// Gets or Sets FittedKitchen
        /// </summary>
        [JsonPropertyName("fitted_kitchen")]
        public bool? FittedKitchen { get { return this.FittedKitchenOption.Value; } set { this.FittedKitchenOption = new(value); } }

        /// <summary>
        /// Used to track the state of Flooring
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FlooringOption { get; private set; }

        /// <summary>
        /// Gets or Sets Flooring
        /// </summary>
        [JsonPropertyName("flooring")]
        public string? Flooring { get { return this.FlooringOption.Value; } set { this.FlooringOption = new(value); } }

        /// <summary>
        /// Used to track the state of Furnished
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FurnishedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Furnished
        /// </summary>
        [JsonPropertyName("furnished")]
        public bool? Furnished { get { return this.FurnishedOption.Value; } set { this.FurnishedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Garden
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> GardenOption { get; private set; }

        /// <summary>
        /// Gets or Sets Garden
        /// </summary>
        [JsonPropertyName("garden")]
        public bool? Garden { get { return this.GardenOption.Value; } set { this.GardenOption = new(value); } }

        /// <summary>
        /// Used to track the state of GuestToilet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> GuestToiletOption { get; private set; }

        /// <summary>
        /// Gets or Sets GuestToilet
        /// </summary>
        [JsonPropertyName("guest_toilet")]
        public bool? GuestToilet { get { return this.GuestToiletOption.Value; } set { this.GuestToiletOption = new(value); } }

        /// <summary>
        /// Used to track the state of KitchenType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> KitchenTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets KitchenType
        /// </summary>
        [JsonPropertyName("kitchen_type")]
        public string? KitchenType { get { return this.KitchenTypeOption.Value; } set { this.KitchenTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Lift
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> LiftOption { get; private set; }

        /// <summary>
        /// Gets or Sets Lift
        /// </summary>
        [JsonPropertyName("lift")]
        public bool? Lift { get { return this.LiftOption.Value; } set { this.LiftOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pool
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PoolOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pool
        /// </summary>
        [JsonPropertyName("pool")]
        public bool? Pool { get { return this.PoolOption.Value; } set { this.PoolOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sauna
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SaunaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sauna
        /// </summary>
        [JsonPropertyName("sauna")]
        public bool? Sauna { get { return this.SaunaOption.Value; } set { this.SaunaOption = new(value); } }

        /// <summary>
        /// Used to track the state of SolarPanels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SolarPanelsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SolarPanels
        /// </summary>
        [JsonPropertyName("solar_panels")]
        public bool? SolarPanels { get { return this.SolarPanelsOption.Value; } set { this.SolarPanelsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Terrace
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TerraceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Terrace
        /// </summary>
        [JsonPropertyName("terrace")]
        public bool? Terrace { get { return this.TerraceOption.Value; } set { this.TerraceOption = new(value); } }

        /// <summary>
        /// Used to track the state of WindowGlazing
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WindowGlazingOption { get; private set; }

        /// <summary>
        /// Gets or Sets WindowGlazing
        /// </summary>
        [JsonPropertyName("window_glazing")]
        public string? WindowGlazing { get { return this.WindowGlazingOption.Value; } set { this.WindowGlazingOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Features {\n");
            sb.Append("  AirConditioning: ").Append(AirConditioning).Append("\n");
            sb.Append("  AlarmSystem: ").Append(AlarmSystem).Append("\n");
            sb.Append("  Balcony: ").Append(Balcony).Append("\n");
            sb.Append("  BarrierFree: ").Append(BarrierFree).Append("\n");
            sb.Append("  Cellar: ").Append(Cellar).Append("\n");
            sb.Append("  Fireplace: ").Append(Fireplace).Append("\n");
            sb.Append("  FittedKitchen: ").Append(FittedKitchen).Append("\n");
            sb.Append("  Flooring: ").Append(Flooring).Append("\n");
            sb.Append("  Furnished: ").Append(Furnished).Append("\n");
            sb.Append("  Garden: ").Append(Garden).Append("\n");
            sb.Append("  GuestToilet: ").Append(GuestToilet).Append("\n");
            sb.Append("  KitchenType: ").Append(KitchenType).Append("\n");
            sb.Append("  Lift: ").Append(Lift).Append("\n");
            sb.Append("  Pool: ").Append(Pool).Append("\n");
            sb.Append("  Sauna: ").Append(Sauna).Append("\n");
            sb.Append("  SolarPanels: ").Append(SolarPanels).Append("\n");
            sb.Append("  Terrace: ").Append(Terrace).Append("\n");
            sb.Append("  WindowGlazing: ").Append(WindowGlazing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Features" />
    /// </summary>
    public partial class FeaturesJsonConverter : JsonConverter<Features>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="FeaturesJsonConverter" /> class.
        /// </summary>
        public FeaturesJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Features" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Features Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> airConditioning = default;
            Option<bool?> alarmSystem = default;
            Option<bool?> balcony = default;
            Option<bool?> barrierFree = default;
            Option<bool?> cellar = default;
            Option<bool?> fireplace = default;
            Option<bool?> fittedKitchen = default;
            Option<string?> flooring = default;
            Option<bool?> furnished = default;
            Option<bool?> garden = default;
            Option<bool?> guestToilet = default;
            Option<string?> kitchenType = default;
            Option<bool?> lift = default;
            Option<bool?> pool = default;
            Option<bool?> sauna = default;
            Option<bool?> solarPanels = default;
            Option<bool?> terrace = default;
            Option<string?> windowGlazing = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "air_conditioning":
                            airConditioning = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "alarm_system":
                            alarmSystem = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "balcony":
                            balcony = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "barrier_free":
                            barrierFree = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "cellar":
                            cellar = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "fireplace":
                            fireplace = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "fitted_kitchen":
                            fittedKitchen = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "flooring":
                            flooring = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "furnished":
                            furnished = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "garden":
                            garden = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "guest_toilet":
                            guestToilet = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "kitchen_type":
                            kitchenType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "lift":
                            lift = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "pool":
                            pool = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "sauna":
                            sauna = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "solar_panels":
                            solarPanels = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "terrace":
                            terrace = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "window_glazing":
                            windowGlazing = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (airConditioning.IsSet && airConditioning.Value == null)
                throw new ArgumentNullException(nameof(airConditioning), "Property is not nullable for class Features.");

            if (alarmSystem.IsSet && alarmSystem.Value == null)
                throw new ArgumentNullException(nameof(alarmSystem), "Property is not nullable for class Features.");

            if (balcony.IsSet && balcony.Value == null)
                throw new ArgumentNullException(nameof(balcony), "Property is not nullable for class Features.");

            if (barrierFree.IsSet && barrierFree.Value == null)
                throw new ArgumentNullException(nameof(barrierFree), "Property is not nullable for class Features.");

            if (cellar.IsSet && cellar.Value == null)
                throw new ArgumentNullException(nameof(cellar), "Property is not nullable for class Features.");

            if (fireplace.IsSet && fireplace.Value == null)
                throw new ArgumentNullException(nameof(fireplace), "Property is not nullable for class Features.");

            if (fittedKitchen.IsSet && fittedKitchen.Value == null)
                throw new ArgumentNullException(nameof(fittedKitchen), "Property is not nullable for class Features.");

            if (flooring.IsSet && flooring.Value == null)
                throw new ArgumentNullException(nameof(flooring), "Property is not nullable for class Features.");

            if (furnished.IsSet && furnished.Value == null)
                throw new ArgumentNullException(nameof(furnished), "Property is not nullable for class Features.");

            if (garden.IsSet && garden.Value == null)
                throw new ArgumentNullException(nameof(garden), "Property is not nullable for class Features.");

            if (guestToilet.IsSet && guestToilet.Value == null)
                throw new ArgumentNullException(nameof(guestToilet), "Property is not nullable for class Features.");

            if (kitchenType.IsSet && kitchenType.Value == null)
                throw new ArgumentNullException(nameof(kitchenType), "Property is not nullable for class Features.");

            if (lift.IsSet && lift.Value == null)
                throw new ArgumentNullException(nameof(lift), "Property is not nullable for class Features.");

            if (pool.IsSet && pool.Value == null)
                throw new ArgumentNullException(nameof(pool), "Property is not nullable for class Features.");

            if (sauna.IsSet && sauna.Value == null)
                throw new ArgumentNullException(nameof(sauna), "Property is not nullable for class Features.");

            if (solarPanels.IsSet && solarPanels.Value == null)
                throw new ArgumentNullException(nameof(solarPanels), "Property is not nullable for class Features.");

            if (terrace.IsSet && terrace.Value == null)
                throw new ArgumentNullException(nameof(terrace), "Property is not nullable for class Features.");

            if (windowGlazing.IsSet && windowGlazing.Value == null)
                throw new ArgumentNullException(nameof(windowGlazing), "Property is not nullable for class Features.");

            return new Features(airConditioning, alarmSystem, balcony, barrierFree, cellar, fireplace, fittedKitchen, flooring, furnished, garden, guestToilet, kitchenType, lift, pool, sauna, solarPanels, terrace, windowGlazing);
        }

        /// <summary>
        /// Serializes a <see cref="Features" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="features"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Features features, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, features, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Features" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="features"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Features features, JsonSerializerOptions jsonSerializerOptions)
        {
            if (features.FlooringOption.IsSet && features.Flooring == null)
                throw new ArgumentNullException(nameof(features.Flooring), "Property is required for class Features.");

            if (features.KitchenTypeOption.IsSet && features.KitchenType == null)
                throw new ArgumentNullException(nameof(features.KitchenType), "Property is required for class Features.");

            if (features.WindowGlazingOption.IsSet && features.WindowGlazing == null)
                throw new ArgumentNullException(nameof(features.WindowGlazing), "Property is required for class Features.");

            if (features.AirConditioningOption.IsSet)
                writer.WriteBoolean("air_conditioning", features.AirConditioningOption.Value!.Value);

            if (features.AlarmSystemOption.IsSet)
                writer.WriteBoolean("alarm_system", features.AlarmSystemOption.Value!.Value);

            if (features.BalconyOption.IsSet)
                writer.WriteBoolean("balcony", features.BalconyOption.Value!.Value);

            if (features.BarrierFreeOption.IsSet)
                writer.WriteBoolean("barrier_free", features.BarrierFreeOption.Value!.Value);

            if (features.CellarOption.IsSet)
                writer.WriteBoolean("cellar", features.CellarOption.Value!.Value);

            if (features.FireplaceOption.IsSet)
                writer.WriteBoolean("fireplace", features.FireplaceOption.Value!.Value);

            if (features.FittedKitchenOption.IsSet)
                writer.WriteBoolean("fitted_kitchen", features.FittedKitchenOption.Value!.Value);

            if (features.FlooringOption.IsSet)
                writer.WriteString("flooring", features.Flooring);

            if (features.FurnishedOption.IsSet)
                writer.WriteBoolean("furnished", features.FurnishedOption.Value!.Value);

            if (features.GardenOption.IsSet)
                writer.WriteBoolean("garden", features.GardenOption.Value!.Value);

            if (features.GuestToiletOption.IsSet)
                writer.WriteBoolean("guest_toilet", features.GuestToiletOption.Value!.Value);

            if (features.KitchenTypeOption.IsSet)
                writer.WriteString("kitchen_type", features.KitchenType);

            if (features.LiftOption.IsSet)
                writer.WriteBoolean("lift", features.LiftOption.Value!.Value);

            if (features.PoolOption.IsSet)
                writer.WriteBoolean("pool", features.PoolOption.Value!.Value);

            if (features.SaunaOption.IsSet)
                writer.WriteBoolean("sauna", features.SaunaOption.Value!.Value);

            if (features.SolarPanelsOption.IsSet)
                writer.WriteBoolean("solar_panels", features.SolarPanelsOption.Value!.Value);

            if (features.TerraceOption.IsSet)
                writer.WriteBoolean("terrace", features.TerraceOption.Value!.Value);

            if (features.WindowGlazingOption.IsSet)
                writer.WriteString("window_glazing", features.WindowGlazing);
        }
    }
}
