/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Generation
    /// </summary>
    [DataContract(Name = "Generation")]
    public partial class Generation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Generation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Generation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Generation" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="failureReason">failureReason.</param>
        /// <param name="finishedAt">finishedAt.</param>
        /// <param name="id">id (required).</param>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="kind">kind (required).</param>
        /// <param name="prompt">prompt.</param>
        /// <param name="propertyId">propertyId.</param>
        /// <param name="roomType">roomType.</param>
        /// <param name="sourceImageId">sourceImageId.</param>
        /// <param name="status">status (required).</param>
        /// <param name="style">style.</param>
        public Generation(DateTime createdAt = default, string failureReason = default, DateTime finishedAt = default, string id = default, string imageUrl = default, string kind = default, string prompt = default, string propertyId = default, string roomType = default, string sourceImageId = default, string status = default, string style = default)
        {
            this.CreatedAt = createdAt;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Generation and cannot be null");
            }
            this.Id = id;
            // to ensure "kind" is required (not null)
            if (kind == null)
            {
                throw new ArgumentNullException("kind is a required property for Generation and cannot be null");
            }
            this.Kind = kind;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Generation and cannot be null");
            }
            this.Status = status;
            this.FailureReason = failureReason;
            this.FinishedAt = finishedAt;
            this.ImageUrl = imageUrl;
            this.Prompt = prompt;
            this.PropertyId = propertyId;
            this.RoomType = roomType;
            this.SourceImageId = sourceImageId;
            this.Style = style;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets FailureReason
        /// </summary>
        [DataMember(Name = "failure_reason", EmitDefaultValue = false)]
        public string FailureReason { get; set; }

        /// <summary>
        /// Gets or Sets FinishedAt
        /// </summary>
        [DataMember(Name = "finished_at", EmitDefaultValue = false)]
        public DateTime FinishedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", EmitDefaultValue = false)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public string Kind { get; set; }

        /// <summary>
        /// Gets or Sets Prompt
        /// </summary>
        [DataMember(Name = "prompt", EmitDefaultValue = false)]
        public string Prompt { get; set; }

        /// <summary>
        /// Gets or Sets PropertyId
        /// </summary>
        [DataMember(Name = "property_id", EmitDefaultValue = false)]
        public string PropertyId { get; set; }

        /// <summary>
        /// Gets or Sets RoomType
        /// </summary>
        [DataMember(Name = "room_type", EmitDefaultValue = false)]
        public string RoomType { get; set; }

        /// <summary>
        /// Gets or Sets SourceImageId
        /// </summary>
        [DataMember(Name = "source_image_id", EmitDefaultValue = false)]
        public string SourceImageId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Style
        /// </summary>
        [DataMember(Name = "style", EmitDefaultValue = false)]
        public string Style { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Generation {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  FailureReason: ").Append(FailureReason).Append("\n");
            sb.Append("  FinishedAt: ").Append(FinishedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  PropertyId: ").Append(PropertyId).Append("\n");
            sb.Append("  RoomType: ").Append(RoomType).Append("\n");
            sb.Append("  SourceImageId: ").Append(SourceImageId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Style: ").Append(Style).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
