// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// ListingInput
    /// </summary>
    public partial class ListingInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingInput" /> class.
        /// </summary>
        /// <param name="currency">currency</param>
        /// <param name="deposit">deposit</param>
        /// <param name="price">price</param>
        /// <param name="pricePeriod">pricePeriod</param>
        /// <param name="serviceCharges">serviceCharges</param>
        /// <param name="status">status</param>
        /// <param name="transactionType">transactionType</param>
        [JsonConstructor]
        public ListingInput(Option<string?> currency = default, Option<decimal?> deposit = default, Option<decimal?> price = default, Option<string?> pricePeriod = default, Option<decimal?> serviceCharges = default, Option<string?> status = default, Option<string?> transactionType = default)
        {
            CurrencyOption = currency;
            DepositOption = deposit;
            PriceOption = price;
            PricePeriodOption = pricePeriod;
            ServiceChargesOption = serviceCharges;
            StatusOption = status;
            TransactionTypeOption = transactionType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Currency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public string? Currency { get { return this.CurrencyOption.Value; } set { this.CurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Deposit
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> DepositOption { get; private set; }

        /// <summary>
        /// Gets or Sets Deposit
        /// </summary>
        [JsonPropertyName("deposit")]
        public decimal? Deposit { get { return this.DepositOption.Value; } set { this.DepositOption = new(value); } }

        /// <summary>
        /// Used to track the state of Price
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PriceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [JsonPropertyName("price")]
        public decimal? Price { get { return this.PriceOption.Value; } set { this.PriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of PricePeriod
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PricePeriodOption { get; private set; }

        /// <summary>
        /// Gets or Sets PricePeriod
        /// </summary>
        [JsonPropertyName("price_period")]
        public string? PricePeriod { get { return this.PricePeriodOption.Value; } set { this.PricePeriodOption = new(value); } }

        /// <summary>
        /// Used to track the state of ServiceCharges
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ServiceChargesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ServiceCharges
        /// </summary>
        [JsonPropertyName("service_charges")]
        public decimal? ServiceCharges { get { return this.ServiceChargesOption.Value; } set { this.ServiceChargesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionType
        /// </summary>
        [JsonPropertyName("transaction_type")]
        public string? TransactionType { get { return this.TransactionTypeOption.Value; } set { this.TransactionTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListingInput {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Deposit: ").Append(Deposit).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PricePeriod: ").Append(PricePeriod).Append("\n");
            sb.Append("  ServiceCharges: ").Append(ServiceCharges).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListingInput" />
    /// </summary>
    public partial class ListingInputJsonConverter : JsonConverter<ListingInput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListingInputJsonConverter" /> class.
        /// </summary>
        public ListingInputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ListingInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListingInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> currency = default;
            Option<decimal?> deposit = default;
            Option<decimal?> price = default;
            Option<string?> pricePeriod = default;
            Option<decimal?> serviceCharges = default;
            Option<string?> status = default;
            Option<string?> transactionType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "currency":
                            currency = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "deposit":
                            deposit = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "price":
                            price = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "price_period":
                            pricePeriod = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "service_charges":
                            serviceCharges = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "transaction_type":
                            transactionType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (currency.IsSet && currency.Value == null)
                throw new ArgumentNullException(nameof(currency), "Property is not nullable for class ListingInput.");

            if (deposit.IsSet && deposit.Value == null)
                throw new ArgumentNullException(nameof(deposit), "Property is not nullable for class ListingInput.");

            if (price.IsSet && price.Value == null)
                throw new ArgumentNullException(nameof(price), "Property is not nullable for class ListingInput.");

            if (pricePeriod.IsSet && pricePeriod.Value == null)
                throw new ArgumentNullException(nameof(pricePeriod), "Property is not nullable for class ListingInput.");

            if (serviceCharges.IsSet && serviceCharges.Value == null)
                throw new ArgumentNullException(nameof(serviceCharges), "Property is not nullable for class ListingInput.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ListingInput.");

            if (transactionType.IsSet && transactionType.Value == null)
                throw new ArgumentNullException(nameof(transactionType), "Property is not nullable for class ListingInput.");

            return new ListingInput(currency, deposit, price, pricePeriod, serviceCharges, status, transactionType);
        }

        /// <summary>
        /// Serializes a <see cref="ListingInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listingInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListingInput listingInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listingInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListingInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listingInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListingInput listingInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listingInput.CurrencyOption.IsSet && listingInput.Currency == null)
                throw new ArgumentNullException(nameof(listingInput.Currency), "Property is required for class ListingInput.");

            if (listingInput.PricePeriodOption.IsSet && listingInput.PricePeriod == null)
                throw new ArgumentNullException(nameof(listingInput.PricePeriod), "Property is required for class ListingInput.");

            if (listingInput.StatusOption.IsSet && listingInput.Status == null)
                throw new ArgumentNullException(nameof(listingInput.Status), "Property is required for class ListingInput.");

            if (listingInput.TransactionTypeOption.IsSet && listingInput.TransactionType == null)
                throw new ArgumentNullException(nameof(listingInput.TransactionType), "Property is required for class ListingInput.");

            if (listingInput.CurrencyOption.IsSet)
                writer.WriteString("currency", listingInput.Currency);

            if (listingInput.DepositOption.IsSet)
                writer.WriteNumber("deposit", listingInput.DepositOption.Value!.Value);

            if (listingInput.PriceOption.IsSet)
                writer.WriteNumber("price", listingInput.PriceOption.Value!.Value);

            if (listingInput.PricePeriodOption.IsSet)
                writer.WriteString("price_period", listingInput.PricePeriod);

            if (listingInput.ServiceChargesOption.IsSet)
                writer.WriteNumber("service_charges", listingInput.ServiceChargesOption.Value!.Value);

            if (listingInput.StatusOption.IsSet)
                writer.WriteString("status", listingInput.Status);

            if (listingInput.TransactionTypeOption.IsSet)
                writer.WriteString("transaction_type", listingInput.TransactionType);
        }
    }
}
