/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// MarketMetric
    /// </summary>
    [DataContract(Name = "MarketMetric")]
    public partial class MarketMetric : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketMetric" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarketMetric() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketMetric" /> class.
        /// </summary>
        /// <param name="changePct">changePct.</param>
        /// <param name="computedAt">computedAt (required).</param>
        /// <param name="currency">currency.</param>
        /// <param name="name">name (required).</param>
        /// <param name="sampleSize">sampleSize.</param>
        /// <param name="unit">unit.</param>
        /// <param name="value">value.</param>
        public MarketMetric(decimal changePct = default, DateTime computedAt = default, string currency = default, string name = default, int sampleSize = default, string unit = default, decimal value = default)
        {
            this.ComputedAt = computedAt;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for MarketMetric and cannot be null");
            }
            this.Name = name;
            this.ChangePct = changePct;
            this.Currency = currency;
            this.SampleSize = sampleSize;
            this.Unit = unit;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets ChangePct
        /// </summary>
        [DataMember(Name = "change_pct", EmitDefaultValue = false)]
        public decimal ChangePct { get; set; }

        /// <summary>
        /// Gets or Sets ComputedAt
        /// </summary>
        [DataMember(Name = "computed_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ComputedAt { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets SampleSize
        /// </summary>
        [DataMember(Name = "sample_size", EmitDefaultValue = false)]
        public int SampleSize { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", EmitDefaultValue = false)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public decimal Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarketMetric {\n");
            sb.Append("  ChangePct: ").Append(ChangePct).Append("\n");
            sb.Append("  ComputedAt: ").Append(ComputedAt).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SampleSize: ").Append(SampleSize).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
