// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// ProblemErrorsInner
    /// </summary>
    public partial class ProblemErrorsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemErrorsInner" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="detail">detail</param>
        /// <param name="field">field</param>
        [JsonConstructor]
        public ProblemErrorsInner(Option<string?> code = default, Option<string?> detail = default, Option<string?> field = default)
        {
            CodeOption = code;
            DetailOption = detail;
            FieldOption = field;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        /* <example>invalid</example> */
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption.Value; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Detail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DetailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Detail
        /// </summary>
        /* <example>Must be a positive whole number of minor units.</example> */
        [JsonPropertyName("detail")]
        public string? Detail { get { return this.DetailOption.Value; } set { this.DetailOption = new(value); } }

        /// <summary>
        /// Used to track the state of Field
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FieldOption { get; private set; }

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        /* <example>price</example> */
        [JsonPropertyName("field")]
        public string? Field { get { return this.FieldOption.Value; } set { this.FieldOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProblemErrorsInner {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProblemErrorsInner" />
    /// </summary>
    public partial class ProblemErrorsInnerJsonConverter : JsonConverter<ProblemErrorsInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ProblemErrorsInnerJsonConverter" /> class.
        /// </summary>
        public ProblemErrorsInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ProblemErrorsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProblemErrorsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> code = default;
            Option<string?> detail = default;
            Option<string?> field = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "detail":
                            detail = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "field":
                            field = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class ProblemErrorsInner.");

            if (detail.IsSet && detail.Value == null)
                throw new ArgumentNullException(nameof(detail), "Property is not nullable for class ProblemErrorsInner.");

            if (field.IsSet && field.Value == null)
                throw new ArgumentNullException(nameof(field), "Property is not nullable for class ProblemErrorsInner.");

            return new ProblemErrorsInner(code, detail, field);
        }

        /// <summary>
        /// Serializes a <see cref="ProblemErrorsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="problemErrorsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProblemErrorsInner problemErrorsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, problemErrorsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProblemErrorsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="problemErrorsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProblemErrorsInner problemErrorsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (problemErrorsInner.CodeOption.IsSet && problemErrorsInner.Code == null)
                throw new ArgumentNullException(nameof(problemErrorsInner.Code), "Property is required for class ProblemErrorsInner.");

            if (problemErrorsInner.DetailOption.IsSet && problemErrorsInner.Detail == null)
                throw new ArgumentNullException(nameof(problemErrorsInner.Detail), "Property is required for class ProblemErrorsInner.");

            if (problemErrorsInner.FieldOption.IsSet && problemErrorsInner.Field == null)
                throw new ArgumentNullException(nameof(problemErrorsInner.Field), "Property is required for class ProblemErrorsInner.");

            if (problemErrorsInner.CodeOption.IsSet)
                writer.WriteString("code", problemErrorsInner.Code);

            if (problemErrorsInner.DetailOption.IsSet)
                writer.WriteString("detail", problemErrorsInner.Detail);

            if (problemErrorsInner.FieldOption.IsSet)
                writer.WriteString("field", problemErrorsInner.Field);
        }
    }
}
