// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// PropertyInput
    /// </summary>
    public partial class PropertyInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyInput" /> class.
        /// </summary>
        /// <param name="addressCity">addressCity</param>
        /// <param name="addressCountry">addressCountry</param>
        /// <param name="addressDistrict">addressDistrict</param>
        /// <param name="addressNumber">addressNumber</param>
        /// <param name="addressPostalCode">addressPostalCode</param>
        /// <param name="addressProvince">addressProvince</param>
        /// <param name="addressStreet">addressStreet</param>
        /// <param name="bathrooms">bathrooms</param>
        /// <param name="bedrooms">bedrooms</param>
        /// <param name="condition">condition</param>
        /// <param name="constructionType">constructionType</param>
        /// <param name="description">description</param>
        /// <param name="energyConsumptionKwh">energyConsumptionKwh</param>
        /// <param name="energyLabel">energyLabel</param>
        /// <param name="externalId">externalId</param>
        /// <param name="floor">floor</param>
        /// <param name="floorsInBuilding">floorsInBuilding</param>
        /// <param name="halfBathrooms">halfBathrooms</param>
        /// <param name="heatingType">heatingType</param>
        /// <param name="latitude">latitude</param>
        /// <param name="listing">listing</param>
        /// <param name="livingAreaSqm">livingAreaSqm</param>
        /// <param name="locationPrecision">locationPrecision</param>
        /// <param name="longitude">longitude</param>
        /// <param name="plotAreaSqm">plotAreaSqm</param>
        /// <param name="title">title</param>
        /// <param name="totalRooms">totalRooms</param>
        /// <param name="type">type</param>
        /// <param name="usableAreaSqm">usableAreaSqm</param>
        /// <param name="yearBuilt">yearBuilt</param>
        /// <param name="yearRenovated">yearRenovated</param>
        [JsonConstructor]
        public PropertyInput(Option<string?> addressCity = default, Option<string?> addressCountry = default, Option<string?> addressDistrict = default, Option<string?> addressNumber = default, Option<string?> addressPostalCode = default, Option<string?> addressProvince = default, Option<string?> addressStreet = default, Option<int?> bathrooms = default, Option<int?> bedrooms = default, Option<string?> condition = default, Option<string?> constructionType = default, Option<string?> description = default, Option<decimal?> energyConsumptionKwh = default, Option<string?> energyLabel = default, Option<string?> externalId = default, Option<int?> floor = default, Option<int?> floorsInBuilding = default, Option<int?> halfBathrooms = default, Option<string?> heatingType = default, Option<decimal?> latitude = default, Option<ListingInput?> listing = default, Option<decimal?> livingAreaSqm = default, Option<string?> locationPrecision = default, Option<decimal?> longitude = default, Option<decimal?> plotAreaSqm = default, Option<string?> title = default, Option<int?> totalRooms = default, Option<string?> type = default, Option<decimal?> usableAreaSqm = default, Option<int?> yearBuilt = default, Option<int?> yearRenovated = default)
        {
            AddressCityOption = addressCity;
            AddressCountryOption = addressCountry;
            AddressDistrictOption = addressDistrict;
            AddressNumberOption = addressNumber;
            AddressPostalCodeOption = addressPostalCode;
            AddressProvinceOption = addressProvince;
            AddressStreetOption = addressStreet;
            BathroomsOption = bathrooms;
            BedroomsOption = bedrooms;
            ConditionOption = condition;
            ConstructionTypeOption = constructionType;
            DescriptionOption = description;
            EnergyConsumptionKwhOption = energyConsumptionKwh;
            EnergyLabelOption = energyLabel;
            ExternalIdOption = externalId;
            FloorOption = floor;
            FloorsInBuildingOption = floorsInBuilding;
            HalfBathroomsOption = halfBathrooms;
            HeatingTypeOption = heatingType;
            LatitudeOption = latitude;
            ListingOption = listing;
            LivingAreaSqmOption = livingAreaSqm;
            LocationPrecisionOption = locationPrecision;
            LongitudeOption = longitude;
            PlotAreaSqmOption = plotAreaSqm;
            TitleOption = title;
            TotalRoomsOption = totalRooms;
            TypeOption = type;
            UsableAreaSqmOption = usableAreaSqm;
            YearBuiltOption = yearBuilt;
            YearRenovatedOption = yearRenovated;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AddressCity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressCityOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressCity
        /// </summary>
        [JsonPropertyName("address_city")]
        public string? AddressCity { get { return this.AddressCityOption.Value; } set { this.AddressCityOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressCountry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressCountryOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressCountry
        /// </summary>
        [JsonPropertyName("address_country")]
        public string? AddressCountry { get { return this.AddressCountryOption.Value; } set { this.AddressCountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressDistrict
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressDistrictOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressDistrict
        /// </summary>
        [JsonPropertyName("address_district")]
        public string? AddressDistrict { get { return this.AddressDistrictOption.Value; } set { this.AddressDistrictOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressNumber
        /// </summary>
        [JsonPropertyName("address_number")]
        public string? AddressNumber { get { return this.AddressNumberOption.Value; } set { this.AddressNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressPostalCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressPostalCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressPostalCode
        /// </summary>
        [JsonPropertyName("address_postal_code")]
        public string? AddressPostalCode { get { return this.AddressPostalCodeOption.Value; } set { this.AddressPostalCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressProvince
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressProvinceOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressProvince
        /// </summary>
        [JsonPropertyName("address_province")]
        public string? AddressProvince { get { return this.AddressProvinceOption.Value; } set { this.AddressProvinceOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressStreet
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressStreetOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressStreet
        /// </summary>
        [JsonPropertyName("address_street")]
        public string? AddressStreet { get { return this.AddressStreetOption.Value; } set { this.AddressStreetOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bathrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BathroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bathrooms
        /// </summary>
        [JsonPropertyName("bathrooms")]
        public int? Bathrooms { get { return this.BathroomsOption.Value; } set { this.BathroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bedrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BedroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bedrooms
        /// </summary>
        [JsonPropertyName("bedrooms")]
        public int? Bedrooms { get { return this.BedroomsOption.Value; } set { this.BedroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Condition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConditionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Condition
        /// </summary>
        [JsonPropertyName("condition")]
        public string? Condition { get { return this.ConditionOption.Value; } set { this.ConditionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConstructionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConstructionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConstructionType
        /// </summary>
        [JsonPropertyName("construction_type")]
        public string? ConstructionType { get { return this.ConstructionTypeOption.Value; } set { this.ConstructionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnergyConsumptionKwh
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> EnergyConsumptionKwhOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnergyConsumptionKwh
        /// </summary>
        [JsonPropertyName("energy_consumption_kwh")]
        public decimal? EnergyConsumptionKwh { get { return this.EnergyConsumptionKwhOption.Value; } set { this.EnergyConsumptionKwhOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnergyLabel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnergyLabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnergyLabel
        /// </summary>
        [JsonPropertyName("energy_label")]
        public string? EnergyLabel { get { return this.EnergyLabelOption.Value; } set { this.EnergyLabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("external_id")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Floor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FloorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Floor
        /// </summary>
        [JsonPropertyName("floor")]
        public int? Floor { get { return this.FloorOption.Value; } set { this.FloorOption = new(value); } }

        /// <summary>
        /// Used to track the state of FloorsInBuilding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FloorsInBuildingOption { get; private set; }

        /// <summary>
        /// Gets or Sets FloorsInBuilding
        /// </summary>
        [JsonPropertyName("floors_in_building")]
        public int? FloorsInBuilding { get { return this.FloorsInBuildingOption.Value; } set { this.FloorsInBuildingOption = new(value); } }

        /// <summary>
        /// Used to track the state of HalfBathrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HalfBathroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets HalfBathrooms
        /// </summary>
        [JsonPropertyName("half_bathrooms")]
        public int? HalfBathrooms { get { return this.HalfBathroomsOption.Value; } set { this.HalfBathroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of HeatingType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HeatingTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets HeatingType
        /// </summary>
        [JsonPropertyName("heating_type")]
        public string? HeatingType { get { return this.HeatingTypeOption.Value; } set { this.HeatingTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Latitude
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LatitudeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [JsonPropertyName("latitude")]
        public decimal? Latitude { get { return this.LatitudeOption.Value; } set { this.LatitudeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Listing
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ListingInput?> ListingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Listing
        /// </summary>
        [JsonPropertyName("listing")]
        public ListingInput? Listing { get { return this.ListingOption.Value; } set { this.ListingOption = new(value); } }

        /// <summary>
        /// Used to track the state of LivingAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LivingAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets LivingAreaSqm
        /// </summary>
        [JsonPropertyName("living_area_sqm")]
        public decimal? LivingAreaSqm { get { return this.LivingAreaSqmOption.Value; } set { this.LivingAreaSqmOption = new(value); } }

        /// <summary>
        /// Used to track the state of LocationPrecision
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LocationPrecisionOption { get; private set; }

        /// <summary>
        /// Gets or Sets LocationPrecision
        /// </summary>
        [JsonPropertyName("location_precision")]
        public string? LocationPrecision { get { return this.LocationPrecisionOption.Value; } set { this.LocationPrecisionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Longitude
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LongitudeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [JsonPropertyName("longitude")]
        public decimal? Longitude { get { return this.LongitudeOption.Value; } set { this.LongitudeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlotAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PlotAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlotAreaSqm
        /// </summary>
        [JsonPropertyName("plot_area_sqm")]
        public decimal? PlotAreaSqm { get { return this.PlotAreaSqmOption.Value; } set { this.PlotAreaSqmOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption.Value; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalRooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalRoomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalRooms
        /// </summary>
        [JsonPropertyName("total_rooms")]
        public int? TotalRooms { get { return this.TotalRoomsOption.Value; } set { this.TotalRoomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsableAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> UsableAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsableAreaSqm
        /// </summary>
        [JsonPropertyName("usable_area_sqm")]
        public decimal? UsableAreaSqm { get { return this.UsableAreaSqmOption.Value; } set { this.UsableAreaSqmOption = new(value); } }

        /// <summary>
        /// Used to track the state of YearBuilt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> YearBuiltOption { get; private set; }

        /// <summary>
        /// Gets or Sets YearBuilt
        /// </summary>
        [JsonPropertyName("year_built")]
        public int? YearBuilt { get { return this.YearBuiltOption.Value; } set { this.YearBuiltOption = new(value); } }

        /// <summary>
        /// Used to track the state of YearRenovated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> YearRenovatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets YearRenovated
        /// </summary>
        [JsonPropertyName("year_renovated")]
        public int? YearRenovated { get { return this.YearRenovatedOption.Value; } set { this.YearRenovatedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PropertyInput {\n");
            sb.Append("  AddressCity: ").Append(AddressCity).Append("\n");
            sb.Append("  AddressCountry: ").Append(AddressCountry).Append("\n");
            sb.Append("  AddressDistrict: ").Append(AddressDistrict).Append("\n");
            sb.Append("  AddressNumber: ").Append(AddressNumber).Append("\n");
            sb.Append("  AddressPostalCode: ").Append(AddressPostalCode).Append("\n");
            sb.Append("  AddressProvince: ").Append(AddressProvince).Append("\n");
            sb.Append("  AddressStreet: ").Append(AddressStreet).Append("\n");
            sb.Append("  Bathrooms: ").Append(Bathrooms).Append("\n");
            sb.Append("  Bedrooms: ").Append(Bedrooms).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  ConstructionType: ").Append(ConstructionType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EnergyConsumptionKwh: ").Append(EnergyConsumptionKwh).Append("\n");
            sb.Append("  EnergyLabel: ").Append(EnergyLabel).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Floor: ").Append(Floor).Append("\n");
            sb.Append("  FloorsInBuilding: ").Append(FloorsInBuilding).Append("\n");
            sb.Append("  HalfBathrooms: ").Append(HalfBathrooms).Append("\n");
            sb.Append("  HeatingType: ").Append(HeatingType).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Listing: ").Append(Listing).Append("\n");
            sb.Append("  LivingAreaSqm: ").Append(LivingAreaSqm).Append("\n");
            sb.Append("  LocationPrecision: ").Append(LocationPrecision).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  PlotAreaSqm: ").Append(PlotAreaSqm).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  TotalRooms: ").Append(TotalRooms).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  UsableAreaSqm: ").Append(UsableAreaSqm).Append("\n");
            sb.Append("  YearBuilt: ").Append(YearBuilt).Append("\n");
            sb.Append("  YearRenovated: ").Append(YearRenovated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PropertyInput" />
    /// </summary>
    public partial class PropertyInputJsonConverter : JsonConverter<PropertyInput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyInputJsonConverter" /> class.
        /// </summary>
        public PropertyInputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="PropertyInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PropertyInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> addressCity = default;
            Option<string?> addressCountry = default;
            Option<string?> addressDistrict = default;
            Option<string?> addressNumber = default;
            Option<string?> addressPostalCode = default;
            Option<string?> addressProvince = default;
            Option<string?> addressStreet = default;
            Option<int?> bathrooms = default;
            Option<int?> bedrooms = default;
            Option<string?> condition = default;
            Option<string?> constructionType = default;
            Option<string?> description = default;
            Option<decimal?> energyConsumptionKwh = default;
            Option<string?> energyLabel = default;
            Option<string?> externalId = default;
            Option<int?> floor = default;
            Option<int?> floorsInBuilding = default;
            Option<int?> halfBathrooms = default;
            Option<string?> heatingType = default;
            Option<decimal?> latitude = default;
            Option<ListingInput?> listing = default;
            Option<decimal?> livingAreaSqm = default;
            Option<string?> locationPrecision = default;
            Option<decimal?> longitude = default;
            Option<decimal?> plotAreaSqm = default;
            Option<string?> title = default;
            Option<int?> totalRooms = default;
            Option<string?> type = default;
            Option<decimal?> usableAreaSqm = default;
            Option<int?> yearBuilt = default;
            Option<int?> yearRenovated = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address_city":
                            addressCity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_country":
                            addressCountry = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_district":
                            addressDistrict = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_number":
                            addressNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_postal_code":
                            addressPostalCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_province":
                            addressProvince = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_street":
                            addressStreet = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "bathrooms":
                            bathrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bedrooms":
                            bedrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "condition":
                            condition = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "construction_type":
                            constructionType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "energy_consumption_kwh":
                            energyConsumptionKwh = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "energy_label":
                            energyLabel = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "external_id":
                            externalId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "floor":
                            floor = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "floors_in_building":
                            floorsInBuilding = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "half_bathrooms":
                            halfBathrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "heating_type":
                            heatingType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "latitude":
                            latitude = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "listing":
                            listing = new Option<ListingInput?>(JsonSerializer.Deserialize<ListingInput>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "living_area_sqm":
                            livingAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "location_precision":
                            locationPrecision = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "longitude":
                            longitude = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "plot_area_sqm":
                            plotAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "total_rooms":
                            totalRooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "usable_area_sqm":
                            usableAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "year_built":
                            yearBuilt = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "year_renovated":
                            yearRenovated = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (addressCity.IsSet && addressCity.Value == null)
                throw new ArgumentNullException(nameof(addressCity), "Property is not nullable for class PropertyInput.");

            if (addressCountry.IsSet && addressCountry.Value == null)
                throw new ArgumentNullException(nameof(addressCountry), "Property is not nullable for class PropertyInput.");

            if (addressDistrict.IsSet && addressDistrict.Value == null)
                throw new ArgumentNullException(nameof(addressDistrict), "Property is not nullable for class PropertyInput.");

            if (addressNumber.IsSet && addressNumber.Value == null)
                throw new ArgumentNullException(nameof(addressNumber), "Property is not nullable for class PropertyInput.");

            if (addressPostalCode.IsSet && addressPostalCode.Value == null)
                throw new ArgumentNullException(nameof(addressPostalCode), "Property is not nullable for class PropertyInput.");

            if (addressProvince.IsSet && addressProvince.Value == null)
                throw new ArgumentNullException(nameof(addressProvince), "Property is not nullable for class PropertyInput.");

            if (addressStreet.IsSet && addressStreet.Value == null)
                throw new ArgumentNullException(nameof(addressStreet), "Property is not nullable for class PropertyInput.");

            if (bathrooms.IsSet && bathrooms.Value == null)
                throw new ArgumentNullException(nameof(bathrooms), "Property is not nullable for class PropertyInput.");

            if (bedrooms.IsSet && bedrooms.Value == null)
                throw new ArgumentNullException(nameof(bedrooms), "Property is not nullable for class PropertyInput.");

            if (condition.IsSet && condition.Value == null)
                throw new ArgumentNullException(nameof(condition), "Property is not nullable for class PropertyInput.");

            if (constructionType.IsSet && constructionType.Value == null)
                throw new ArgumentNullException(nameof(constructionType), "Property is not nullable for class PropertyInput.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class PropertyInput.");

            if (energyConsumptionKwh.IsSet && energyConsumptionKwh.Value == null)
                throw new ArgumentNullException(nameof(energyConsumptionKwh), "Property is not nullable for class PropertyInput.");

            if (energyLabel.IsSet && energyLabel.Value == null)
                throw new ArgumentNullException(nameof(energyLabel), "Property is not nullable for class PropertyInput.");

            if (externalId.IsSet && externalId.Value == null)
                throw new ArgumentNullException(nameof(externalId), "Property is not nullable for class PropertyInput.");

            if (floor.IsSet && floor.Value == null)
                throw new ArgumentNullException(nameof(floor), "Property is not nullable for class PropertyInput.");

            if (floorsInBuilding.IsSet && floorsInBuilding.Value == null)
                throw new ArgumentNullException(nameof(floorsInBuilding), "Property is not nullable for class PropertyInput.");

            if (halfBathrooms.IsSet && halfBathrooms.Value == null)
                throw new ArgumentNullException(nameof(halfBathrooms), "Property is not nullable for class PropertyInput.");

            if (heatingType.IsSet && heatingType.Value == null)
                throw new ArgumentNullException(nameof(heatingType), "Property is not nullable for class PropertyInput.");

            if (latitude.IsSet && latitude.Value == null)
                throw new ArgumentNullException(nameof(latitude), "Property is not nullable for class PropertyInput.");

            if (listing.IsSet && listing.Value == null)
                throw new ArgumentNullException(nameof(listing), "Property is not nullable for class PropertyInput.");

            if (livingAreaSqm.IsSet && livingAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(livingAreaSqm), "Property is not nullable for class PropertyInput.");

            if (locationPrecision.IsSet && locationPrecision.Value == null)
                throw new ArgumentNullException(nameof(locationPrecision), "Property is not nullable for class PropertyInput.");

            if (longitude.IsSet && longitude.Value == null)
                throw new ArgumentNullException(nameof(longitude), "Property is not nullable for class PropertyInput.");

            if (plotAreaSqm.IsSet && plotAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(plotAreaSqm), "Property is not nullable for class PropertyInput.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class PropertyInput.");

            if (totalRooms.IsSet && totalRooms.Value == null)
                throw new ArgumentNullException(nameof(totalRooms), "Property is not nullable for class PropertyInput.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PropertyInput.");

            if (usableAreaSqm.IsSet && usableAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(usableAreaSqm), "Property is not nullable for class PropertyInput.");

            if (yearBuilt.IsSet && yearBuilt.Value == null)
                throw new ArgumentNullException(nameof(yearBuilt), "Property is not nullable for class PropertyInput.");

            if (yearRenovated.IsSet && yearRenovated.Value == null)
                throw new ArgumentNullException(nameof(yearRenovated), "Property is not nullable for class PropertyInput.");

            return new PropertyInput(addressCity, addressCountry, addressDistrict, addressNumber, addressPostalCode, addressProvince, addressStreet, bathrooms, bedrooms, condition, constructionType, description, energyConsumptionKwh, energyLabel, externalId, floor, floorsInBuilding, halfBathrooms, heatingType, latitude, listing, livingAreaSqm, locationPrecision, longitude, plotAreaSqm, title, totalRooms, type, usableAreaSqm, yearBuilt, yearRenovated);
        }

        /// <summary>
        /// Serializes a <see cref="PropertyInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="propertyInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PropertyInput propertyInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, propertyInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PropertyInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="propertyInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PropertyInput propertyInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (propertyInput.AddressCityOption.IsSet && propertyInput.AddressCity == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressCity), "Property is required for class PropertyInput.");

            if (propertyInput.AddressCountryOption.IsSet && propertyInput.AddressCountry == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressCountry), "Property is required for class PropertyInput.");

            if (propertyInput.AddressDistrictOption.IsSet && propertyInput.AddressDistrict == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressDistrict), "Property is required for class PropertyInput.");

            if (propertyInput.AddressNumberOption.IsSet && propertyInput.AddressNumber == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressNumber), "Property is required for class PropertyInput.");

            if (propertyInput.AddressPostalCodeOption.IsSet && propertyInput.AddressPostalCode == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressPostalCode), "Property is required for class PropertyInput.");

            if (propertyInput.AddressProvinceOption.IsSet && propertyInput.AddressProvince == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressProvince), "Property is required for class PropertyInput.");

            if (propertyInput.AddressStreetOption.IsSet && propertyInput.AddressStreet == null)
                throw new ArgumentNullException(nameof(propertyInput.AddressStreet), "Property is required for class PropertyInput.");

            if (propertyInput.ConditionOption.IsSet && propertyInput.Condition == null)
                throw new ArgumentNullException(nameof(propertyInput.Condition), "Property is required for class PropertyInput.");

            if (propertyInput.ConstructionTypeOption.IsSet && propertyInput.ConstructionType == null)
                throw new ArgumentNullException(nameof(propertyInput.ConstructionType), "Property is required for class PropertyInput.");

            if (propertyInput.DescriptionOption.IsSet && propertyInput.Description == null)
                throw new ArgumentNullException(nameof(propertyInput.Description), "Property is required for class PropertyInput.");

            if (propertyInput.EnergyLabelOption.IsSet && propertyInput.EnergyLabel == null)
                throw new ArgumentNullException(nameof(propertyInput.EnergyLabel), "Property is required for class PropertyInput.");

            if (propertyInput.ExternalIdOption.IsSet && propertyInput.ExternalId == null)
                throw new ArgumentNullException(nameof(propertyInput.ExternalId), "Property is required for class PropertyInput.");

            if (propertyInput.HeatingTypeOption.IsSet && propertyInput.HeatingType == null)
                throw new ArgumentNullException(nameof(propertyInput.HeatingType), "Property is required for class PropertyInput.");

            if (propertyInput.ListingOption.IsSet && propertyInput.Listing == null)
                throw new ArgumentNullException(nameof(propertyInput.Listing), "Property is required for class PropertyInput.");

            if (propertyInput.LocationPrecisionOption.IsSet && propertyInput.LocationPrecision == null)
                throw new ArgumentNullException(nameof(propertyInput.LocationPrecision), "Property is required for class PropertyInput.");

            if (propertyInput.TitleOption.IsSet && propertyInput.Title == null)
                throw new ArgumentNullException(nameof(propertyInput.Title), "Property is required for class PropertyInput.");

            if (propertyInput.TypeOption.IsSet && propertyInput.Type == null)
                throw new ArgumentNullException(nameof(propertyInput.Type), "Property is required for class PropertyInput.");

            if (propertyInput.AddressCityOption.IsSet)
                writer.WriteString("address_city", propertyInput.AddressCity);

            if (propertyInput.AddressCountryOption.IsSet)
                writer.WriteString("address_country", propertyInput.AddressCountry);

            if (propertyInput.AddressDistrictOption.IsSet)
                writer.WriteString("address_district", propertyInput.AddressDistrict);

            if (propertyInput.AddressNumberOption.IsSet)
                writer.WriteString("address_number", propertyInput.AddressNumber);

            if (propertyInput.AddressPostalCodeOption.IsSet)
                writer.WriteString("address_postal_code", propertyInput.AddressPostalCode);

            if (propertyInput.AddressProvinceOption.IsSet)
                writer.WriteString("address_province", propertyInput.AddressProvince);

            if (propertyInput.AddressStreetOption.IsSet)
                writer.WriteString("address_street", propertyInput.AddressStreet);

            if (propertyInput.BathroomsOption.IsSet)
                writer.WriteNumber("bathrooms", propertyInput.BathroomsOption.Value!.Value);

            if (propertyInput.BedroomsOption.IsSet)
                writer.WriteNumber("bedrooms", propertyInput.BedroomsOption.Value!.Value);

            if (propertyInput.ConditionOption.IsSet)
                writer.WriteString("condition", propertyInput.Condition);

            if (propertyInput.ConstructionTypeOption.IsSet)
                writer.WriteString("construction_type", propertyInput.ConstructionType);

            if (propertyInput.DescriptionOption.IsSet)
                writer.WriteString("description", propertyInput.Description);

            if (propertyInput.EnergyConsumptionKwhOption.IsSet)
                writer.WriteNumber("energy_consumption_kwh", propertyInput.EnergyConsumptionKwhOption.Value!.Value);

            if (propertyInput.EnergyLabelOption.IsSet)
                writer.WriteString("energy_label", propertyInput.EnergyLabel);

            if (propertyInput.ExternalIdOption.IsSet)
                writer.WriteString("external_id", propertyInput.ExternalId);

            if (propertyInput.FloorOption.IsSet)
                writer.WriteNumber("floor", propertyInput.FloorOption.Value!.Value);

            if (propertyInput.FloorsInBuildingOption.IsSet)
                writer.WriteNumber("floors_in_building", propertyInput.FloorsInBuildingOption.Value!.Value);

            if (propertyInput.HalfBathroomsOption.IsSet)
                writer.WriteNumber("half_bathrooms", propertyInput.HalfBathroomsOption.Value!.Value);

            if (propertyInput.HeatingTypeOption.IsSet)
                writer.WriteString("heating_type", propertyInput.HeatingType);

            if (propertyInput.LatitudeOption.IsSet)
                writer.WriteNumber("latitude", propertyInput.LatitudeOption.Value!.Value);

            if (propertyInput.ListingOption.IsSet)
            {
                writer.WritePropertyName("listing");
                JsonSerializer.Serialize(writer, propertyInput.Listing, jsonSerializerOptions);
            }
            if (propertyInput.LivingAreaSqmOption.IsSet)
                writer.WriteNumber("living_area_sqm", propertyInput.LivingAreaSqmOption.Value!.Value);

            if (propertyInput.LocationPrecisionOption.IsSet)
                writer.WriteString("location_precision", propertyInput.LocationPrecision);

            if (propertyInput.LongitudeOption.IsSet)
                writer.WriteNumber("longitude", propertyInput.LongitudeOption.Value!.Value);

            if (propertyInput.PlotAreaSqmOption.IsSet)
                writer.WriteNumber("plot_area_sqm", propertyInput.PlotAreaSqmOption.Value!.Value);

            if (propertyInput.TitleOption.IsSet)
                writer.WriteString("title", propertyInput.Title);

            if (propertyInput.TotalRoomsOption.IsSet)
                writer.WriteNumber("total_rooms", propertyInput.TotalRoomsOption.Value!.Value);

            if (propertyInput.TypeOption.IsSet)
                writer.WriteString("type", propertyInput.Type);

            if (propertyInput.UsableAreaSqmOption.IsSet)
                writer.WriteNumber("usable_area_sqm", propertyInput.UsableAreaSqmOption.Value!.Value);

            if (propertyInput.YearBuiltOption.IsSet)
                writer.WriteNumber("year_built", propertyInput.YearBuiltOption.Value!.Value);

            if (propertyInput.YearRenovatedOption.IsSet)
                writer.WriteNumber("year_renovated", propertyInput.YearRenovatedOption.Value!.Value);
        }
    }
}
