/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Rooms
    /// </summary>
    [DataContract(Name = "Rooms")]
    public partial class Rooms : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rooms" /> class.
        /// </summary>
        /// <param name="bathrooms">bathrooms.</param>
        /// <param name="bedrooms">bedrooms.</param>
        /// <param name="floor">floor.</param>
        /// <param name="floorsInBuilding">floorsInBuilding.</param>
        /// <param name="halfBathrooms">halfBathrooms.</param>
        /// <param name="totalRooms">totalRooms.</param>
        public Rooms(int bathrooms = default, int bedrooms = default, int floor = default, int floorsInBuilding = default, int halfBathrooms = default, int totalRooms = default)
        {
            this.Bathrooms = bathrooms;
            this.Bedrooms = bedrooms;
            this.Floor = floor;
            this.FloorsInBuilding = floorsInBuilding;
            this.HalfBathrooms = halfBathrooms;
            this.TotalRooms = totalRooms;
        }

        /// <summary>
        /// Gets or Sets Bathrooms
        /// </summary>
        [DataMember(Name = "bathrooms", EmitDefaultValue = false)]
        public int Bathrooms { get; set; }

        /// <summary>
        /// Gets or Sets Bedrooms
        /// </summary>
        [DataMember(Name = "bedrooms", EmitDefaultValue = false)]
        public int Bedrooms { get; set; }

        /// <summary>
        /// Gets or Sets Floor
        /// </summary>
        [DataMember(Name = "floor", EmitDefaultValue = false)]
        public int Floor { get; set; }

        /// <summary>
        /// Gets or Sets FloorsInBuilding
        /// </summary>
        [DataMember(Name = "floors_in_building", EmitDefaultValue = false)]
        public int FloorsInBuilding { get; set; }

        /// <summary>
        /// Gets or Sets HalfBathrooms
        /// </summary>
        [DataMember(Name = "half_bathrooms", EmitDefaultValue = false)]
        public int HalfBathrooms { get; set; }

        /// <summary>
        /// Gets or Sets TotalRooms
        /// </summary>
        [DataMember(Name = "total_rooms", EmitDefaultValue = false)]
        public int TotalRooms { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rooms {\n");
            sb.Append("  Bathrooms: ").Append(Bathrooms).Append("\n");
            sb.Append("  Bedrooms: ").Append(Bedrooms).Append("\n");
            sb.Append("  Floor: ").Append(Floor).Append("\n");
            sb.Append("  FloorsInBuilding: ").Append(FloorsInBuilding).Append("\n");
            sb.Append("  HalfBathrooms: ").Append(HalfBathrooms).Append("\n");
            sb.Append("  TotalRooms: ").Append(TotalRooms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
