// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Rooms
    /// </summary>
    public partial class Rooms : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rooms" /> class.
        /// </summary>
        /// <param name="bathrooms">bathrooms</param>
        /// <param name="bedrooms">bedrooms</param>
        /// <param name="floor">floor</param>
        /// <param name="floorsInBuilding">floorsInBuilding</param>
        /// <param name="halfBathrooms">halfBathrooms</param>
        /// <param name="totalRooms">totalRooms</param>
        [JsonConstructor]
        public Rooms(Option<int?> bathrooms = default, Option<int?> bedrooms = default, Option<int?> floor = default, Option<int?> floorsInBuilding = default, Option<int?> halfBathrooms = default, Option<int?> totalRooms = default)
        {
            BathroomsOption = bathrooms;
            BedroomsOption = bedrooms;
            FloorOption = floor;
            FloorsInBuildingOption = floorsInBuilding;
            HalfBathroomsOption = halfBathrooms;
            TotalRoomsOption = totalRooms;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Bathrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BathroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bathrooms
        /// </summary>
        [JsonPropertyName("bathrooms")]
        public int? Bathrooms { get { return this.BathroomsOption.Value; } set { this.BathroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Bedrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BedroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bedrooms
        /// </summary>
        [JsonPropertyName("bedrooms")]
        public int? Bedrooms { get { return this.BedroomsOption.Value; } set { this.BedroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Floor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FloorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Floor
        /// </summary>
        [JsonPropertyName("floor")]
        public int? Floor { get { return this.FloorOption.Value; } set { this.FloorOption = new(value); } }

        /// <summary>
        /// Used to track the state of FloorsInBuilding
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FloorsInBuildingOption { get; private set; }

        /// <summary>
        /// Gets or Sets FloorsInBuilding
        /// </summary>
        [JsonPropertyName("floors_in_building")]
        public int? FloorsInBuilding { get { return this.FloorsInBuildingOption.Value; } set { this.FloorsInBuildingOption = new(value); } }

        /// <summary>
        /// Used to track the state of HalfBathrooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> HalfBathroomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets HalfBathrooms
        /// </summary>
        [JsonPropertyName("half_bathrooms")]
        public int? HalfBathrooms { get { return this.HalfBathroomsOption.Value; } set { this.HalfBathroomsOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalRooms
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalRoomsOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalRooms
        /// </summary>
        [JsonPropertyName("total_rooms")]
        public int? TotalRooms { get { return this.TotalRoomsOption.Value; } set { this.TotalRoomsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rooms {\n");
            sb.Append("  Bathrooms: ").Append(Bathrooms).Append("\n");
            sb.Append("  Bedrooms: ").Append(Bedrooms).Append("\n");
            sb.Append("  Floor: ").Append(Floor).Append("\n");
            sb.Append("  FloorsInBuilding: ").Append(FloorsInBuilding).Append("\n");
            sb.Append("  HalfBathrooms: ").Append(HalfBathrooms).Append("\n");
            sb.Append("  TotalRooms: ").Append(TotalRooms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Rooms" />
    /// </summary>
    public partial class RoomsJsonConverter : JsonConverter<Rooms>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="RoomsJsonConverter" /> class.
        /// </summary>
        public RoomsJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Rooms" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Rooms Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> bathrooms = default;
            Option<int?> bedrooms = default;
            Option<int?> floor = default;
            Option<int?> floorsInBuilding = default;
            Option<int?> halfBathrooms = default;
            Option<int?> totalRooms = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bathrooms":
                            bathrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "bedrooms":
                            bedrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "floor":
                            floor = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "floors_in_building":
                            floorsInBuilding = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "half_bathrooms":
                            halfBathrooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_rooms":
                            totalRooms = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (bathrooms.IsSet && bathrooms.Value == null)
                throw new ArgumentNullException(nameof(bathrooms), "Property is not nullable for class Rooms.");

            if (bedrooms.IsSet && bedrooms.Value == null)
                throw new ArgumentNullException(nameof(bedrooms), "Property is not nullable for class Rooms.");

            if (floor.IsSet && floor.Value == null)
                throw new ArgumentNullException(nameof(floor), "Property is not nullable for class Rooms.");

            if (floorsInBuilding.IsSet && floorsInBuilding.Value == null)
                throw new ArgumentNullException(nameof(floorsInBuilding), "Property is not nullable for class Rooms.");

            if (halfBathrooms.IsSet && halfBathrooms.Value == null)
                throw new ArgumentNullException(nameof(halfBathrooms), "Property is not nullable for class Rooms.");

            if (totalRooms.IsSet && totalRooms.Value == null)
                throw new ArgumentNullException(nameof(totalRooms), "Property is not nullable for class Rooms.");

            return new Rooms(bathrooms, bedrooms, floor, floorsInBuilding, halfBathrooms, totalRooms);
        }

        /// <summary>
        /// Serializes a <see cref="Rooms" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rooms"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Rooms rooms, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rooms, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Rooms" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rooms"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Rooms rooms, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rooms.BathroomsOption.IsSet)
                writer.WriteNumber("bathrooms", rooms.BathroomsOption.Value!.Value);

            if (rooms.BedroomsOption.IsSet)
                writer.WriteNumber("bedrooms", rooms.BedroomsOption.Value!.Value);

            if (rooms.FloorOption.IsSet)
                writer.WriteNumber("floor", rooms.FloorOption.Value!.Value);

            if (rooms.FloorsInBuildingOption.IsSet)
                writer.WriteNumber("floors_in_building", rooms.FloorsInBuildingOption.Value!.Value);

            if (rooms.HalfBathroomsOption.IsSet)
                writer.WriteNumber("half_bathrooms", rooms.HalfBathroomsOption.Value!.Value);

            if (rooms.TotalRoomsOption.IsSet)
                writer.WriteNumber("total_rooms", rooms.TotalRoomsOption.Value!.Value);
        }
    }
}
