/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Skautik.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Skautik.Sdk.Client.OpenAPIDateConverter;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// SeriesPoint
    /// </summary>
    [DataContract(Name = "SeriesPoint")]
    public partial class SeriesPoint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesPoint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeriesPoint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesPoint" /> class.
        /// </summary>
        /// <param name="listingCount">listingCount (required).</param>
        /// <param name="medianDaysListed">medianDaysListed.</param>
        /// <param name="medianPrice">medianPrice.</param>
        /// <param name="medianPricePerArea">medianPricePerArea.</param>
        /// <param name="period">period (required).</param>
        public SeriesPoint(int listingCount = default, int medianDaysListed = default, decimal medianPrice = default, decimal medianPricePerArea = default, string period = default)
        {
            this.ListingCount = listingCount;
            // to ensure "period" is required (not null)
            if (period == null)
            {
                throw new ArgumentNullException("period is a required property for SeriesPoint and cannot be null");
            }
            this.Period = period;
            this.MedianDaysListed = medianDaysListed;
            this.MedianPrice = medianPrice;
            this.MedianPricePerArea = medianPricePerArea;
        }

        /// <summary>
        /// Gets or Sets ListingCount
        /// </summary>
        [DataMember(Name = "listing_count", IsRequired = true, EmitDefaultValue = true)]
        public int ListingCount { get; set; }

        /// <summary>
        /// Gets or Sets MedianDaysListed
        /// </summary>
        [DataMember(Name = "median_days_listed", EmitDefaultValue = false)]
        public int MedianDaysListed { get; set; }

        /// <summary>
        /// Gets or Sets MedianPrice
        /// </summary>
        [DataMember(Name = "median_price", EmitDefaultValue = false)]
        public decimal MedianPrice { get; set; }

        /// <summary>
        /// Gets or Sets MedianPricePerArea
        /// </summary>
        [DataMember(Name = "median_price_per_area", EmitDefaultValue = false)]
        public decimal MedianPricePerArea { get; set; }

        /// <summary>
        /// Gets or Sets Period
        /// </summary>
        [DataMember(Name = "period", IsRequired = true, EmitDefaultValue = true)]
        public string Period { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeriesPoint {\n");
            sb.Append("  ListingCount: ").Append(ListingCount).Append("\n");
            sb.Append("  MedianDaysListed: ").Append(MedianDaysListed).Append("\n");
            sb.Append("  MedianPrice: ").Append(MedianPrice).Append("\n");
            sb.Append("  MedianPricePerArea: ").Append(MedianPricePerArea).Append("\n");
            sb.Append("  Period: ").Append(Period).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
