// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// ShrinkGuard
    /// </summary>
    public partial class ShrinkGuard : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShrinkGuard" /> class.
        /// </summary>
        /// <param name="baseline">baseline</param>
        /// <param name="delivered">delivered</param>
        /// <param name="ratio">ratio</param>
        /// <param name="tripped">tripped</param>
        /// <param name="withdrawalsSkipped">withdrawalsSkipped</param>
        [JsonConstructor]
        public ShrinkGuard(int baseline, int delivered, decimal ratio, bool tripped, int withdrawalsSkipped)
        {
            Baseline = baseline;
            Delivered = delivered;
            Ratio = ratio;
            Tripped = tripped;
            WithdrawalsSkipped = withdrawalsSkipped;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Baseline
        /// </summary>
        [JsonPropertyName("baseline")]
        public int Baseline { get; set; }

        /// <summary>
        /// Gets or Sets Delivered
        /// </summary>
        [JsonPropertyName("delivered")]
        public int Delivered { get; set; }

        /// <summary>
        /// Gets or Sets Ratio
        /// </summary>
        [JsonPropertyName("ratio")]
        public decimal Ratio { get; set; }

        /// <summary>
        /// Gets or Sets Tripped
        /// </summary>
        [JsonPropertyName("tripped")]
        public bool Tripped { get; set; }

        /// <summary>
        /// Gets or Sets WithdrawalsSkipped
        /// </summary>
        [JsonPropertyName("withdrawals_skipped")]
        public int WithdrawalsSkipped { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShrinkGuard {\n");
            sb.Append("  Baseline: ").Append(Baseline).Append("\n");
            sb.Append("  Delivered: ").Append(Delivered).Append("\n");
            sb.Append("  Ratio: ").Append(Ratio).Append("\n");
            sb.Append("  Tripped: ").Append(Tripped).Append("\n");
            sb.Append("  WithdrawalsSkipped: ").Append(WithdrawalsSkipped).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ShrinkGuard" />
    /// </summary>
    public partial class ShrinkGuardJsonConverter : JsonConverter<ShrinkGuard>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ShrinkGuardJsonConverter" /> class.
        /// </summary>
        public ShrinkGuardJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ShrinkGuard" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ShrinkGuard Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> baseline = default;
            Option<int?> delivered = default;
            Option<decimal?> ratio = default;
            Option<bool?> tripped = default;
            Option<int?> withdrawalsSkipped = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "baseline":
                            baseline = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "delivered":
                            delivered = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "ratio":
                            ratio = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "tripped":
                            tripped = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "withdrawals_skipped":
                            withdrawalsSkipped = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!baseline.IsSet)
                throw new ArgumentException("Property is required for class ShrinkGuard.", nameof(baseline));

            if (!delivered.IsSet)
                throw new ArgumentException("Property is required for class ShrinkGuard.", nameof(delivered));

            if (!ratio.IsSet)
                throw new ArgumentException("Property is required for class ShrinkGuard.", nameof(ratio));

            if (!tripped.IsSet)
                throw new ArgumentException("Property is required for class ShrinkGuard.", nameof(tripped));

            if (!withdrawalsSkipped.IsSet)
                throw new ArgumentException("Property is required for class ShrinkGuard.", nameof(withdrawalsSkipped));

            if (baseline.IsSet && baseline.Value == null)
                throw new ArgumentNullException(nameof(baseline), "Property is not nullable for class ShrinkGuard.");

            if (delivered.IsSet && delivered.Value == null)
                throw new ArgumentNullException(nameof(delivered), "Property is not nullable for class ShrinkGuard.");

            if (ratio.IsSet && ratio.Value == null)
                throw new ArgumentNullException(nameof(ratio), "Property is not nullable for class ShrinkGuard.");

            if (tripped.IsSet && tripped.Value == null)
                throw new ArgumentNullException(nameof(tripped), "Property is not nullable for class ShrinkGuard.");

            if (withdrawalsSkipped.IsSet && withdrawalsSkipped.Value == null)
                throw new ArgumentNullException(nameof(withdrawalsSkipped), "Property is not nullable for class ShrinkGuard.");

            return new ShrinkGuard(baseline.Value!.Value!, delivered.Value!.Value!, ratio.Value!.Value!, tripped.Value!.Value!, withdrawalsSkipped.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ShrinkGuard" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shrinkGuard"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ShrinkGuard shrinkGuard, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, shrinkGuard, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ShrinkGuard" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shrinkGuard"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ShrinkGuard shrinkGuard, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("baseline", shrinkGuard.Baseline);

            writer.WriteNumber("delivered", shrinkGuard.Delivered);

            writer.WriteNumber("ratio", shrinkGuard.Ratio);

            writer.WriteBoolean("tripped", shrinkGuard.Tripped);

            writer.WriteNumber("withdrawals_skipped", shrinkGuard.WithdrawalsSkipped);
        }
    }
}
