// <auto-generated>
/*
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Skautik.Sdk.Client;

namespace Skautik.Sdk.Model
{
    /// <summary>
    /// Size
    /// </summary>
    public partial class Size : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Size" /> class.
        /// </summary>
        /// <param name="livingAreaSqm">livingAreaSqm</param>
        /// <param name="plotAreaSqm">plotAreaSqm</param>
        /// <param name="usableAreaSqm">usableAreaSqm</param>
        [JsonConstructor]
        public Size(Option<decimal?> livingAreaSqm = default, Option<decimal?> plotAreaSqm = default, Option<decimal?> usableAreaSqm = default)
        {
            LivingAreaSqmOption = livingAreaSqm;
            PlotAreaSqmOption = plotAreaSqm;
            UsableAreaSqmOption = usableAreaSqm;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LivingAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> LivingAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets LivingAreaSqm
        /// </summary>
        [JsonPropertyName("living_area_sqm")]
        public decimal? LivingAreaSqm { get { return this.LivingAreaSqmOption.Value; } set { this.LivingAreaSqmOption = new(value); } }

        /// <summary>
        /// Used to track the state of PlotAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> PlotAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlotAreaSqm
        /// </summary>
        [JsonPropertyName("plot_area_sqm")]
        public decimal? PlotAreaSqm { get { return this.PlotAreaSqmOption.Value; } set { this.PlotAreaSqmOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsableAreaSqm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> UsableAreaSqmOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsableAreaSqm
        /// </summary>
        [JsonPropertyName("usable_area_sqm")]
        public decimal? UsableAreaSqm { get { return this.UsableAreaSqmOption.Value; } set { this.UsableAreaSqmOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Size {\n");
            sb.Append("  LivingAreaSqm: ").Append(LivingAreaSqm).Append("\n");
            sb.Append("  PlotAreaSqm: ").Append(PlotAreaSqm).Append("\n");
            sb.Append("  UsableAreaSqm: ").Append(UsableAreaSqm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Size" />
    /// </summary>
    public partial class SizeJsonConverter : JsonConverter<Size>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SizeJsonConverter" /> class.
        /// </summary>
        public SizeJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Size" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Size Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> livingAreaSqm = default;
            Option<decimal?> plotAreaSqm = default;
            Option<decimal?> usableAreaSqm = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "living_area_sqm":
                            livingAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "plot_area_sqm":
                            plotAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "usable_area_sqm":
                            usableAreaSqm = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (livingAreaSqm.IsSet && livingAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(livingAreaSqm), "Property is not nullable for class Size.");

            if (plotAreaSqm.IsSet && plotAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(plotAreaSqm), "Property is not nullable for class Size.");

            if (usableAreaSqm.IsSet && usableAreaSqm.Value == null)
                throw new ArgumentNullException(nameof(usableAreaSqm), "Property is not nullable for class Size.");

            return new Size(livingAreaSqm, plotAreaSqm, usableAreaSqm);
        }

        /// <summary>
        /// Serializes a <see cref="Size" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="size"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Size size, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, size, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Size" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="size"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Size size, JsonSerializerOptions jsonSerializerOptions)
        {
            if (size.LivingAreaSqmOption.IsSet)
                writer.WriteNumber("living_area_sqm", size.LivingAreaSqmOption.Value!.Value);

            if (size.PlotAreaSqmOption.IsSet)
                writer.WriteNumber("plot_area_sqm", size.PlotAreaSqmOption.Value!.Value);

            if (size.UsableAreaSqmOption.IsSet)
                writer.WriteNumber("usable_area_sqm", size.UsableAreaSqmOption.Value!.Value);
        }
    }
}
