// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

using System;
using System.Net.Http;
using System.Text.Json;
using Microsoft.Extensions.Logging.Abstractions;
using Skautik.Sdk.Api;
using Skautik.Sdk.Client;

namespace Skautik.Sdk;

/// <summary>
/// The Skautik API.
/// </summary>
/// <remarks>
/// Named SkautikClient rather than Skautik because the root namespace is
/// Skautik: a class of the same name shadows it, and every generated file that
/// writes Skautik.Sdk.Something stops compiling.
/// </remarks>
/// <example>
/// <code>
/// using var skautik = new SkautikClient("sk_live_...");
///
/// var page = await skautik.Properties.ListPropertiesAsync(
///     city: "Berlin",
///     maxPrice: 750_000);
///
/// await foreach (var property in skautik.AllPropertiesAsync(city: "Berlin"))
/// {
///     Console.WriteLine(property.Title);
/// }
/// </code>
/// </example>
/// <remarks>
/// For an application using the generic host, register the generated clients
/// with AddApi instead. This is for everything else, where wiring five
/// dependencies by hand to make one request is not a reasonable ask.
/// </remarks>
public sealed partial class SkautikClient : IDisposable
{
    /// <summary>Endpoints about your key rather than about property.</summary>
    public AccountAndStatusApi Account { get; }

    /// <summary>Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready.</summary>
    public ExportsApi Exports { get; }

    /// <summary>Transform a photograph you have already uploaded: stage an empty room, remove clutter, or correct how a picture was taken. Each request is queued and produced in the background.</summary>
    public ImageGenerationsApi Generations { get; }

    /// <summary>Move inventory in from whatever system already holds it. A one-off import handles a migration; an import source keeps a CRM and Skautik in step indefinitely.</summary>
    public ImportsApi Imports { get; }

    /// <summary>Enquiries people have made about your properties, and the state you have moved each one to. Scoped to the properties your organisation owns: an enquiry belongs to whoever owns the property it is about.</summary>
    public InquiriesApi Inquiries { get; }

    /// <summary>Where we have coverage, how each market is subdivided, and the aggregate statistics computed across it.</summary>
    public MarketsApi Markets { get; }

    /// <summary>The catalogue, and your own inventory within it. Read endpoints span everything we hold; write endpoints only ever touch records your organisation published.</summary>
    public PropertiesApi Properties { get; }

    /// <summary>Subscribe to changes rather than polling for them. A webhook costs nothing against your request quota, which makes it much cheaper than re-reading a market on a timer.</summary>
    public WebhooksApi Webhooks { get; }

    private readonly HttpClient _httpClient;
    private readonly bool _ownsHttpClient;

    /// <param name="apiKey">A key from the developer console.</param>
    /// <param name="baseAddress">Somewhere other than production, for staging or a local server.</param>
    /// <param name="httpClient">An existing client to send through. One is created if none is given, and only a created one is disposed.</param>
    public SkautikClient(string apiKey, Uri? baseAddress = null, HttpClient? httpClient = null)
    {
        if (string.IsNullOrWhiteSpace(apiKey))
        {
            throw new ArgumentException("An API key is required.", nameof(apiKey));
        }

        _ownsHttpClient = httpClient is null;
        _httpClient = httpClient ?? new HttpClient();
        _httpClient.BaseAddress = baseAddress ?? new Uri(ClientUtils.BASE_ADDRESS);

        var serializerOptions = new JsonSerializerOptionsProvider(
            new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            });

        var tokens = new RateLimitProvider<BearerToken>(
            new TokenContainer<BearerToken>(new[] { new BearerToken(apiKey) }));

        Account = new AccountAndStatusApi(
            NullLogger<AccountAndStatusApi>.Instance,
            httpClient,
            serializerOptions,
            new AccountAndStatusApiEvents(),
            tokens);

        Exports = new ExportsApi(
            NullLogger<ExportsApi>.Instance,
            httpClient,
            serializerOptions,
            new ExportsApiEvents(),
            tokens);

        Generations = new ImageGenerationsApi(
            NullLogger<ImageGenerationsApi>.Instance,
            httpClient,
            serializerOptions,
            new ImageGenerationsApiEvents(),
            tokens);

        Imports = new ImportsApi(
            NullLogger<ImportsApi>.Instance,
            httpClient,
            serializerOptions,
            new ImportsApiEvents(),
            tokens);

        Inquiries = new InquiriesApi(
            NullLogger<InquiriesApi>.Instance,
            httpClient,
            serializerOptions,
            new InquiriesApiEvents(),
            tokens);

        Markets = new MarketsApi(
            NullLogger<MarketsApi>.Instance,
            httpClient,
            serializerOptions,
            new MarketsApiEvents(),
            tokens);

        Properties = new PropertiesApi(
            NullLogger<PropertiesApi>.Instance,
            httpClient,
            serializerOptions,
            new PropertiesApiEvents(),
            tokens);

        Webhooks = new WebhooksApi(
            NullLogger<WebhooksApi>.Instance,
            httpClient,
            serializerOptions,
            new WebhooksApiEvents(),
            tokens);
    }

    /// <inheritdoc />
    public void Dispose()
    {
        if (_ownsHttpClient)
        {
            _httpClient.Dispose();
        }
    }
}
